#!/usr/bin/env python3
"""m8shift.py — single-file multi-agent relay (M8Shift), portable to any project.

Model: copy THIS single file to the root of a project, then `./m8shift.py init`.
`init` (re)generates M8SHIFT.md + M8SHIFT.protocol.md and injects the anchors into
CLAUDE.md / AGENTS.md. The lock (mutex) is the LOCK block at the top of M8SHIFT.md,
delimited by the HTML comments M8SHIFT:LOCK:BEGIN / M8SHIFT:LOCK:END. Turns are
delimited by M8SHIFT:TURN <n> <agent> BEGIN / END. See M8SHIFT.protocol.md.

Formerly CoWork: existing projects keep their COWORK.md / COWORK:* files (still read
AND written in place); `m8shift migrate-brand` is the opt-in path that renames them.
`cowork.py` remains a thin deprecated shim that execs this file.

No API key, no network, no daemon: a passive local CLI the agents drive with shell
commands; they bring their own auth, so M8Shift adds zero credentials.
"""
import argparse
import contextlib
import datetime as dt
import json
import os
import re
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
def _pick(new, old):
    """Dual-read resolver: the NEW (M8Shift) name wins when present; else the OLD
    (CoWork) name when present; else the NEW name (fresh `init` writes new names).
    Resolved ONCE at import so the def-time default args of read()/write() below
    capture the resolved path."""
    np = os.path.join(HERE, new)
    op = os.path.join(HERE, old)
    if os.path.exists(np):
        return np
    if os.path.exists(op):
        return op
    return np


# Persistent file names. Existing projects keep their CoWork-named files (read AND
# written in place); `migrate-brand` is the only thing that renames them. The archive
# and protocol brands are DERIVED from the living file so a project never goes split-brand.
COWORK = _pick("M8SHIFT.md", "COWORK.md")               # the living relay file
_LEGACY = os.path.basename(COWORK) == "COWORK.md"       # project still on the old names
ARCHIVE = os.path.join(HERE, "COWORK.archive.md" if _LEGACY else "M8SHIFT.archive.md")
PROTO = os.path.join(HERE, "COWORK.protocol.md" if _LEGACY else "M8SHIFT.protocol.md")
LOCKFILE = _pick(".m8shift.lock", ".cowork.lock")       # inter-process lock (O_EXCL)
LOCK_TIMEOUT = 10        # s: max wait to acquire the internal lock
LOCK_STALE_S = 60        # s: beyond this, a lock file is deemed abandoned
TTL_MIN = 30
LANGS = ("en", "fr")             # supported languages (catalog keys + CLI choices)
DEFAULT_LANG = "en"              # default / ultimate fallback language
AGENTS = ("claude", "codex")     # default active pair (exact backward-compat)
ROSTER = AGENTS                  # current ACTIVE pair (2 agents) — refined at runtime
AGENT_RE = r"[a-z][a-z0-9_-]*"   # normalized agent name (ASCII)
# Reserved marker prefixes — BOTH brands: forbidden in fields, neutralized in bodies.
RESERVED = ("COWORK:TURN", "COWORK:LOCK", "COWORK:STANZA",
            "M8SHIFT:TURN", "M8SHIFT:LOCK", "M8SHIFT:STANZA")

# LOCK / STANZA markers. The NEW (M8SHIFT) forms are the WRITE default for fresh files;
# the OLD (COWORK) forms are still detected and parsed in legacy files. A normal command
# never converts a file's brand (only `migrate-brand` does) — see lock_markers()/stanza_re().
LOCK_BEGIN = "<!-- M8SHIFT:LOCK:BEGIN -->"
LOCK_END = "<!-- M8SHIFT:LOCK:END -->"
OLD_LOCK_BEGIN = "<!-- COWORK:LOCK:BEGIN -->"
OLD_LOCK_END = "<!-- COWORK:LOCK:END -->"
STANZA_BEGIN = "<!-- M8SHIFT:STANZA:BEGIN (generated by m8shift.py init - do not edit by hand) -->"
STANZA_END = "<!-- M8SHIFT:STANZA:END -->"
OLD_STANZA_BEGIN = "<!-- COWORK:STANZA:BEGIN (genere par cowork.py init - ne pas editer a la main) -->"
OLD_STANZA_END = "<!-- COWORK:STANZA:END -->"

# Canonical names auto-loaded by the host tools. Existing variants are renamed to
# these names during `init`, including via a two-step rename on case-insensitive
# filesystems.
CLAUDE_ANCHOR = "CLAUDE.md"
CODEX_ANCHOR = "AGENTS.md"
CODEX_OVERRIDE = "AGENTS.override.md"

# Anchor file auto-loaded by each known agent. Best-effort: an agent missing from
# the table gets a manual-bootstrap warning (cf. RFC roster §5).
ANCHORS = {
    "claude": "CLAUDE.md",
    "codex": "AGENTS.md",
    "gemini": "GEMINI.md",
    "lechat": "AGENTS.md",   # Le Chat / Mistral: best-effort (convention unconfirmed)
    "mistral": "AGENTS.md",
    # NOTE: nested-path anchors (e.g. GitHub Copilot's .github/copilot-instructions.md)
    # are out of stage 1 — ensure_canonical_anchor is not path-aware (no case handling
    # in subdirs). Such an agent falls back to a manual-bootstrap warning.
}

BRIDGE_FR = """## Instructions communes du projet

Lis et applique intégralement `CLAUDE.md`, qui contient les instructions communes
du projet pour Claude et Codex.
"""


# ----------------------------------------------------------------- templates

COWORK_FR = r"""<!-- ╔════════════════════════════════════════════════════════════╗
     ║  M8Shift · relais mono-fichier multi-agents · protocole v1 ║
     ║  Lis M8SHIFT.protocol.md AVANT d'écrire ici.               ║
     ╚════════════════════════════════════════════════════════════╝ -->

# M8Shift · __PROJECT__

> Fichier de travail partagé. **Un seul agent écrit à la fois.** Le verrou est le
> bloc `LOCK` ci-dessous. N'écris que si `state == AWAITING_<toi>`. Détails →
> [M8SHIFT.protocol.md](M8SHIFT.protocol.md). Outil → `./m8shift.py status`.

<!-- M8SHIFT:LOCK:BEGIN -->
holder:   none
state:    IDLE
agents:   __AGENTS__
lang:     __LANG__
turn:     0
since:    __NOW__
expires:  -
note:     session initialisée, aucun tour ouvert
<!-- M8SHIFT:LOCK:END -->

---

## Journal des tours

<!-- Les tours s'empilent ci-dessous, du plus ancien au plus récent.        -->
<!-- Format d'un tour : voir M8SHIFT.protocol.md §3. Ne jamais éditer un tour -->
<!-- déjà clôturé (END posé) : on ajoute un nouveau tour à la place.         -->

<!-- M8SHIFT:TURN 0 system BEGIN -->
- from:    system
- to:      none
- ask:     —
- done:    Initialisation du relais. Le premier agent qui démarre fait
           `./m8shift.py claim __A__` (ou `__B__`), travaille, puis
           `./m8shift.py append __A__ --to __B__ --ask "..." --done "..."`.
- files:   M8SHIFT.md, M8SHIFT.protocol.md, m8shift.py
- handoff: none
<!-- M8SHIFT:TURN 0 system END -->
"""

PROTOCOL_FR = r"""# M8Shift · Protocole de relais mono-fichier (v1)

Instruction commune aux **deux agents actifs** (par défaut **Claude** et **Codex**)
pour coopérer via un seul fichier
`M8SHIFT.md`, en alternance stricte (mutex), avec poll périodique. Portable : ce
protocole est identique dans tout projet ; seul le titre de `M8SHIFT.md` change.

À lire **une fois en début de session** dès que tu vois un `M8SHIFT.md` à la
racine d'un projet. Tu es **l'un des deux agents actifs** déclarés dans le champ
`agents:` de `M8SHIFT.md` (par défaut `claude` et `codex`) — identifie-toi par ton
fichier d'ancrage.

---

## 0. TL;DR — la boucle auto-suffisante

Tu viens d'arriver dans le projet et tu vois un `M8SHIFT.md` : voici la boucle
complète, copiable, **aucune autre instruction n'est nécessaire**. `<toi>` est ton
propre nom d'agent et `<autre>` l'autre agent actif (le couple déclaré dans
`agents:` ; par défaut `claude` / `codex`, via les ancrages `CLAUDE.md` / `AGENTS.md`).

```bash
# 1. Suis-je attendu ? (commandes NON bloquantes)
./m8shift.py status                 # lis le champ `state`
./m8shift.py wait <toi> --once      # rc 0 = tu peux acquérir ; rc 3 = pas encore

# 2. ACQUIERS le stylo AVANT de travailler (acquisition EXCLUSIVE : sur deux agents
#    qui tentent en même temps, un seul réussit) :
./m8shift.py claim <toi>            # rc 0 = tu tiens le stylo ; rc != 0 = pas ton tour
#    • Si claim RÉUSSIT : lis le `ask:` que <autre> t'a laissé dans le dernier
#      tour (en démarrage IDLE/tour 0, rien à honorer), fais le travail dans le
#      dépôt, PUIS enregistre ton tour et passe la main :
./m8shift.py append <toi> --to <autre> \
    --ask "ce que tu attends de l'autre" \
    --done "ce que tu viens de faire" \
    --files fichier1,fichier2
#    • Si claim ÉCHOUE : ce n'est pas (ou plus) ton tour → reviens à l'attente.

# 3. Pas ton tour : ne touche à RIEN. Bloque jusqu'à ton tour, puis reprends en 2 :
./m8shift.py wait <toi>             # poll toutes les ~60 s (--interval N)
```

Règle d'or : **tu ne travailles et n'écris que si tu as acquis le stylo via
`claim`.** `claim` est exclusif ; `append` n'est accepté que si tu tiens le
stylo. Tout le reste de ce document n'est que le détail de cette boucle.

> Le protocole te rend auto-suffisant *une fois que tu tournes*. Dans une UI interactive
> (VS Code, …) un humain te relance quand même entre les tours — `wait` bloque un
> processus, il ne réveille pas ton UI de chat. Un relais entièrement autonome nécessite
> un lanceur headless (sans interface), pas une modification de ce protocole.

---

## 1. Modèle mental

- **Un seul fichier vivant** : `M8SHIFT.md`. Tout le dialogue de travail y est.
- **Un seul stylo, acquis explicitement** : pour travailler, tu **prends** le
  stylo via `claim` → état `WORKING_<toi>`. `claim` est **exclusif** (deux agents
  qui tentent en même temps : un seul réussit). Tu ne modifies le dépôt **que**
  pendant que tu tiens le stylo.
- **`append` clôt ton tour** : il n'est accepté que depuis `WORKING_<toi>`, écrit
  le tour et passe la main (`AWAITING_<autre>`). Pas de `claim` ⇒ pas d'`append`.
- **Alternance stricte** : les deux agents actifs alternent (p. ex. `claude` →
  `codex` → `claude` …). Chaque passage de main est un *tour* (`TURN`) numéroté,
  encadré `BEGIN`/`END`.
- **Poll** : quand ce n'est pas ton tour, tu attends (`./m8shift.py wait <toi>`,
  ~60 s) puis tu retentes `claim`.

---

## 2. Le bloc LOCK (le mutex)

Délimité par `<!-- M8SHIFT:LOCK:BEGIN -->` … `<!-- M8SHIFT:LOCK:END -->`.
Champs (un `clé: valeur` par ligne, faciles à `grep`) :

| champ     | valeurs | sens |
|-----------|---------|------|
| `holder`  | un agent actif \| `none` | qui tient le stylo (défaut `claude`/`codex`) |
| `state`   | `IDLE` \| `WORKING_<X>` \| `AWAITING_<X>` \| `DONE` | état courant (`<X>` = un agent actif, en majuscules) |
| `agents`  | CSV, ex. `claude,codex` | le couple du relais (les 2 premiers déclarés) ; défaut `claude,codex` |
| `turn`    | entier | numéro du dernier tour clôturé |
| `since`   | ISO-8601 UTC | depuis quand cet état dure |
| `expires` | ISO-8601 UTC \| `-` | échéance de reprise anti-blocage (TTL 30 min) |
| `note`    | texte court | mémo lisible |

> `expires` ne porte une date **que** pendant `WORKING_*` (un agent travaille,
> TTL 30 min). Il repasse à `-` dès qu'on attend (`AWAITING_*`, `IDLE`, `DONE`) :
> personne ne tient le stylo, donc pas de péremption à surveiller.

**Lecture des états** (`<X>` = un agent actif — par défaut `claude`/`codex`) :
- `AWAITING_<X>` → c'est à `<X>` de jouer (l'autre agent attend).
- `WORKING_<X>` → `<X>` tient le stylo et travaille (l'autre attend, ne touche à rien).
- `IDLE` → personne n'a la main, le premier qui a quelque chose à dire démarre.
- `DONE` → session close, plus de relais attendu.

---

## 3. Format d'un tour

```
<!-- M8SHIFT:TURN <n> <agent> BEGIN -->
- from:    <agent>           # un agent actif
- to:      <agent|none>      # à qui tu repasses la main
- ask:     <ce que tu attends de l'autre, précis et actionnable>
- done:    <ce que tu viens de faire>
- files:   <fichiers touchés, séparés par des virgules>
- handoff: <agent|none>      # = to ; redondance volontaire, grep-friendly
<ligne vide>
<corps libre : explications, questions, blocs de code, listes>
<!-- M8SHIFT:TURN <n> <agent> END -->
```

Règles :
- Un tour **clôturé** (`END` posé) est **immuable**. Pour réagir, tu ouvres le
  tour suivant. Jamais de réécriture rétroactive.
- `ask` doit être actionnable : l'autre agent doit pouvoir démarrer sans te
  reposer de question. Si tu n'attends rien (juste un FYI), mets `ask: —`.
- Garde un tour **borné** : si ça dépasse ~150 lignes ou plusieurs sujets,
  découpe en plusieurs tours successifs (un sujet = un tour).

---

## 4. Cycle de travail (la boucle de chaque agent)

```
boucle:
  1. lire LOCK (status / wait)
  2. si state == AWAITING_<moi> ou IDLE :
       a. CLAIM  : ./m8shift.py claim <moi>   → state=WORKING_<MOI>, expires=now+30min
                   EXCLUSIF : si un autre a déjà pris le stylo entre-temps,
                   claim ÉCHOUE → va en 3.
       b. TRAVAILLER dans le dépôt (tant que tu tiens le stylo, toi seul)
       c. APPEND  : ./m8shift.py append <moi> --to <autre>
                   écrit mon tour <turn+1>, state=AWAITING_<AUTRE>
  3. sinon (WORKING_<autre> ou AWAITING_<autre>) :
       attendre ~60 s (wait), retourner en 1
  4. si state == DONE : sortir
```

En pratique : `claim` **acquiert** le stylo (exclusif), `append` **clôt** ton tour
et passe la main, `wait` attend ton tour. L'acquisition explicite avant de
travailler est ce qui garantit qu'un seul agent modifie le dépôt à la fois.

> **Modèle de concurrence (deux niveaux)** :
> 1. **Transitions** sérialisées par un verrou inter-process (`.m8shift.lock`,
>    `O_CREAT|O_EXCL`, à jeton de propriété) : chaque read-modify-write du LOCK +
>    écriture atomique (temporaire unique + `os.replace`) est exclusif.
> 2. **Fenêtre de travail** protégée par l'état persistant `WORKING_<agent>` :
>    `claim` est la seule acquisition, et il échoue si quelqu'un d'autre tient ou
>    a déjà pris le stylo. Deux `claim` simultanés depuis `IDLE` ⇒ **un seul
>    réussit** ; l'autre doit attendre. Comme on ne travaille qu'après un `claim`
>    réussi, deux agents ne modifient jamais le dépôt en même temps.
>
> Un `.m8shift.lock` abandonné (process tué) est repris après 60 s, jeton vérifié.
> *Limites* : verrou **conseillé** (une édition manuelle de `M8SHIFT.md` le
> contourne) ; sur FS réseau (NFS) `O_EXCL`/`rename` sont moins fiables — cowork
> vise un dépôt sur disque local. Voir aussi §0/§4 (claim obligatoire).

---

## 5. Anti-blocage (lock périmé)

Si l'autre agent crashe en tenant le stylo, le verrou resterait coincé. Garde-fou :
- au CLAIM, on pose `expires = now + 30 min` ;
- si tu vois `state == WORKING_<autre>` **et** `now > expires`, le verrou est
  **périmé** : reprends-le avec `./m8shift.py claim <toi> --force`, puis ouvre un
  tour notant la reprise (`done: reprise après lock périmé de <autre>`) ;
- **l'outil applique la règle** : `--force` est **refusé** sur un verrou encore
  valide. Tu ne peux donc pas voler le stylo d'un agent actif (c'est voulu) ;
- tu peux **rafraîchir ton propre** verrou avant péremption : `./m8shift.py claim
  <toi>` quand tu le détiens déjà repose `expires` à +30 min ;
- `release` et `done` n'agissent que si **tu** tiens le stylo (ou si personne ne
  le tient) ; `--force` outrepasse, réservé à la récupération.

---

## 6. Tenue dans le temps (longueur bornée)

`M8SHIFT.md` ne doit pas gonfler indéfiniment :
- garde dans `M8SHIFT.md` le bloc `LOCK` + les **~6 derniers tours** ;
- `./m8shift.py archive --keep 6` déplace les tours plus anciens (déjà clôturés)
  vers `M8SHIFT.archive.md` (append), sans jamais toucher au verrou ni au dernier
  tour ouvert.
- L'archive est consultable mais n'est **jamais** relue par la boucle : seule la
  partie vivante de `M8SHIFT.md` pilote le relais.

---

## 7. Outil `m8shift.py`

```
./m8shift.py init [--name PROJET] [--agents a,b] [--lang en|fr] [--force]  # (re)génère le kit ici
./m8shift.py status                                # verrou + dernier tour (NON bloquant)
./m8shift.py wait <agent> [--once] [--interval N]  # attend ton tour ; --once = 1 check (rc 3 si pas ton tour)
./m8shift.py claim <agent> [--force]               # ACQUIERS le stylo (exclusif) — depuis ton tour /
                                                  #   IDLE / ton propre verrou ; --force = verrou périmé SEULEMENT
./m8shift.py append <agent> --to <autre> \
     --ask "..." --done "..." [--files a,b] [--body fichier.md|-]   # clôt ton tour + passe la main
./m8shift.py release <agent> --to <autre> [--force]  # repasser la main sans corps (ne ré-incrémente PAS turn)
./m8shift.py done <agent> [--force]                 # clore la session (state=DONE)
./m8shift.py archive [--keep N]                     # purge les vieux tours clôturés (jamais le tour #0)
```

- **`claim` d'abord** : tu dois tenir le stylo (`WORKING_<toi>`) pour `append`.
  `claim` est **exclusif** (un seul gagnant si deux agents tentent ensemble).
- `append` n'est accepté **que depuis `WORKING_<toi>`** ; il écrit le tour et
  passe la main. `--body -` lit le corps depuis stdin ; `--body f.md` depuis un
  fichier ; sans `--body`, le tour n'a que l'en-tête.
- `--to` doit viser **l'autre** agent (auto-passation refusée : alternance stricte).
- Inspection **non bloquante** : `status` ou `wait <toi> --once`. `wait <toi>`
  **sans** `--once` bloque jusqu'à ton tour — ne l'utilise pas si tu dois rendre
  la main à ta boucle entre-temps.

---

## 8. Adoption par tout projet (portabilité)

`m8shift.py` est **auto-suffisant** : il embarque ce protocole, le gabarit de
`M8SHIFT.md` et les ancrages. Pour adopter le relais dans un projet :

```bash
cp /chemin/vers/m8shift.py .      # copier le seul fichier nécessaire
./m8shift.py init                 # nom du projet = nom du dossier (sinon --name)
```

`init` :
- écrit `M8SHIFT.protocol.md` (ce document) et `M8SHIFT.md` (verrou IDLE neuf) ;
  `M8SHIFT.md` n'est **pas** écrasé s'il existe déjà (sauf `--force`) → l'état du
  relais en cours est préservé ;
- injecte en **tête** un bloc « Co-work relais » dans **l'ancrage de chaque agent
  actif** (par défaut `CLAUDE.md` et `AGENTS.md` ; créés s'ils manquent), entre
  marqueurs `M8SHIFT:STANZA` → ré-injection **idempotente** (déplace/actualise le bloc
  sans dupliquer, contenu existant préservé ; le fichier précédent est sauvegardé dans
  `<ancrage>.cowork.bak`) ;
- si `CLAUDE.md` existait mais qu'aucune instruction Codex (`AGENTS.md` ou
  `AGENTS.override.md`) n'existait, crée automatiquement dans `AGENTS.md` un pont
  demandant à Codex de lire les instructions communes de `CLAUDE.md`. Un ancrage
  Codex préexistant n'est jamais complété ou remplacé automatiquement ;
- renomme une variante unique `claude.md`/`agents.md` vers le nom canonique
  auto-chargé, y compris sur un FS insensible à la casse. Plusieurs variantes
  coexistantes sont refusées plutôt que fusionnées silencieusement. Si Git est
  disponible et que la variante est suivie, emploie `git mv -f` pour actualiser
  aussi l'index ;
- si `AGENTS.override.md` existe, y synchronise aussi la strophe : Codex charge
  cet override à la place de `AGENTS.md` dans le même dossier.

### Amorçage / prise en compte par les agents

cowork est **passif** : il n'« appelle » aucune IA. Il s'appuie sur la convention de
chaque outil hôte — **Claude lit `CLAUDE.md`, Codex lit `AGENTS.md`**, et tout autre
agent actif lit son propre ancrage — au démarrage de session/exécution. La chaîne
d'amorçage est donc :

```mermaid
flowchart LR
    I["m8shift.py init"] --> S["injecte la strophe dans<br/>l'ancrage de chaque agent actif"]
    S --> R["chaque agent lit son ancrage<br/>au démarrage de session"]
    R --> L["applique M8SHIFT.protocol.md<br/>(la boucle wait / claim / travail / append)"]
```

- **Après `init`** : démarre une nouvelle session/exécution de l'agent. Une session
  déjà ouverte a généralement construit sa chaîne d'instructions avant l'injection.
- **Codex interactif ou `codex exec`** : `AGENTS.md` est chargé si la commande part
  de la racine du projet ou d'un de ses sous-dossiers. Le mode *headless* n'est pas
  en soi une limite ; un cron/CI lancé hors du projet, en revanche, ne découvre pas
  l'ancrage.
- **Override Codex** : `AGENTS.override.md` masque `AGENTS.md` dans un même dossier ;
  `init` injecte donc la strophe dans les deux lorsqu'il est présent.
- **Taille Codex** : Codex empile les fichiers d'instructions jusqu'à un plafond
  *combiné* (`project_doc_max_bytes`, 32 Kio par défaut) et tronque le fichier qui
  dépasse au nombre d'octets restant. Mettre la strophe en tête la conserve donc en
  priorité (et un fichier plus proche du cwd prime) ; garde néanmoins les ancrages
  **légers**.
- **Limite générale** : cowork ne peut pas forcer une IA à lire quoi que ce soit.
  Sans racine/contexte projet, pointe explicitement l'agent vers
  `M8SHIFT.protocol.md`.

Référence Codex : https://developers.openai.com/codex/guides/agents-md
"""

STANZA_FR = """{begin}
## Co-work relais — auto-suffisant (aucune explication humaine requise)

Tu es **{me}** dans ce projet. Dès qu'un `M8SHIFT.md` est présent à la racine,
c'est ta source de coordination avec **{other}** : applique `M8SHIFT.protocol.md`
(lis-le une fois, voir son §0) AVANT tout autre travail. **Tu ne travailles et
n'écris que si tu as acquis le stylo via `claim`.**

```bash
./m8shift.py status                # qui a la main ? (non bloquant)
./m8shift.py wait {me} --once      # rc 0 = tu peux acquérir ; rc 3 = pas encore
```

- **Acquiers d'abord** (`state == AWAITING_{ME}` ou `IDLE`) :
  `./m8shift.py claim {me}` — **exclusif** : si {other} a déjà pris le stylo, ça
  échoue → reviens à l'attente. Si ça réussit, tu tiens le stylo (`WORKING_{ME}`).
- **Puis travaille et clôts ton tour** : lis le `ask:` que {other} t'a laissé
  (en démarrage IDLE, rien à honorer), fais le travail, puis :
  `./m8shift.py append {me} --to {other} --ask "…" --done "…" [--files a,b]`
- **Pas ton tour** : ne touche à rien ; `./m8shift.py wait {me}` bloque jusqu'à ton
  tour (poll ~60 s), puis retente `claim`.
- **Verrou de {other} périmé** (`WORKING_{OTHER}` + `now > expires`) :
  `./m8shift.py claim {me} --force`.

Un tour clôturé est immuable : pour réagir, ouvre le tour suivant.

_Note UI interactive_ : dans une UI de chat (VS Code, …) un humain te relance entre les
tours — `wait` bloque un processus, il ne réveille pas ton UI. Un relais entièrement
autonome nécessite un lanceur headless (sans interface).
{end}"""


# ------------------------------------------------------------------- helpers


PROTOCOL_EN = r"""# M8Shift · Single-file relay protocol (v1)

Shared instruction for the **two active agents** (by default **Claude** and
**Codex**) to cooperate through a single
`M8SHIFT.md` file, in strict alternation (mutex), with periodic polling. Portable:
this protocol is identical in every project; only the title of `M8SHIFT.md`
changes.

Read it **once at the start of a session** as soon as you see a `M8SHIFT.md` at
the root of a project. You are **one of the two active agents** declared in the
`agents:` field of `M8SHIFT.md` (by default `claude` and `codex`) — identify yourself
by your anchor file.

---

## 0. TL;DR — the self-contained loop

You have just arrived in the project and you see a `M8SHIFT.md`: here is the
complete, copy-pasteable loop, **no other instruction is required**. `<you>` is your
own agent name and `<other>` is the other active agent (the pair declared in
`agents:`; by default `claude` / `codex`, via the `CLAUDE.md` / `AGENTS.md` anchors).

```bash
# 1. Am I expected? (NON-blocking commands)
./m8shift.py status                 # read the `state` field
./m8shift.py wait <you> --once      # rc 0 = you may acquire ; rc 3 = not yet

# 2. ACQUIRE the pen BEFORE working (EXCLUSIVE acquisition: when two agents
#    try at the same time, only one succeeds):
./m8shift.py claim <you>           # rc 0 = you hold the pen ; rc != 0 = not your turn
#    • If claim SUCCEEDS: read the `ask:` that <other> left you in the last
#      turn (at IDLE startup / turn 0, nothing to honour), do the work in the
#      repository, THEN record your turn and hand off:
./m8shift.py append <you> --to <other> \
    --ask "what you expect from the other" \
    --done "what you just did" \
    --files file1,file2
#    • If claim FAILS: it is not (or no longer) your turn → go back to waiting.

# 3. Not your turn: touch NOTHING. Block until your turn, then resume at 2:
./m8shift.py wait <you>             # poll every ~60 s (--interval N)
```

Golden rule: **you work and write only if you have acquired the pen via
`claim`.** `claim` is exclusive; `append` is accepted only if you hold the
pen. Everything else in this document is just the detail of this loop.

> The protocol makes you self-sufficient *once you are running*. In an interactive UI
> (VS Code, …) a human still resumes you between turns — `wait` blocks a process, it
> does not wake your chat UI. Fully hands-off relays need a headless runner, not a
> change to this protocol.

---

## 1. Mental model

- **A single living file**: `M8SHIFT.md`. The entire work dialogue is there.
- **A single pen, explicitly acquired**: to work, you **take** the pen via
  `claim` → state `WORKING_<you>`. `claim` is **exclusive** (two agents trying
  at the same time: only one succeeds). You modify the repository **only** while
  you hold the pen.
- **`append` closes your turn**: it is accepted only from `WORKING_<you>`,
  writes the turn and hands off (`AWAITING_<other>`). No `claim` ⇒ no `append`.
- **Strict alternation**: the two active agents take turns (e.g. `claude` → `codex`
  → `claude` …). Each hand-off is a numbered *turn* (`TURN`), framed by `BEGIN`/`END`.
- **Poll**: when it is not your turn, you wait (`./m8shift.py wait <you>`,
  ~60 s) then you retry `claim`.

---

## 2. The LOCK block (the mutex)

Delimited by `<!-- M8SHIFT:LOCK:BEGIN -->` … `<!-- M8SHIFT:LOCK:END -->`.
Fields (one `key: value` per line, easy to `grep`):

| field     | values | meaning |
|-----------|---------|------|
| `holder`  | an active agent \| `none` | who holds the pen (default `claude`/`codex`) |
| `state`   | `IDLE` \| `WORKING_<X>` \| `AWAITING_<X>` \| `DONE` | current state (`<X>` = an active agent, uppercased) |
| `agents`  | CSV, e.g. `claude,codex` | the relaying pair (the first two declared); default `claude,codex` |
| `turn`    | integer | number of the last closed turn |
| `since`   | ISO-8601 UTC | since when this state has lasted |
| `expires` | ISO-8601 UTC \| `-` | anti-deadlock takeover deadline (TTL 30 min) |
| `note`    | short text | readable memo |

> `expires` carries a date **only** during `WORKING_*` (an agent is working,
> TTL 30 min). It returns to `-` as soon as we are waiting (`AWAITING_*`, `IDLE`,
> `DONE`): nobody holds the pen, so there is no staleness to watch.

**Reading the states** (`<X>` is an active agent — by default `claude`/`codex`):
- `AWAITING_<X>` → it is `<X>`'s turn to play (the other agent waits).
- `WORKING_<X>` → `<X>` holds the pen and is working (the other waits, touches nothing).
- `IDLE` → nobody has the hand, the first who has something to say starts.
- `DONE` → session closed, no further relay expected.

---

## 3. Format of a turn

```
<!-- M8SHIFT:TURN <n> <agent> BEGIN -->
- from:    <agent>           # an active agent
- to:      <agent|none>      # to whom you hand off
- ask:     <what you expect from the other, precise and actionable>
- done:    <what you just did>
- files:   <files touched, comma-separated>
- handoff: <agent|none>      # = to ; deliberate redundancy, grep-friendly
<blank line>
<free body: explanations, questions, code blocks, lists>
<!-- M8SHIFT:TURN <n> <agent> END -->
```

Rules:
- A **closed** turn (`END` set) is **immutable**. To react, you open the next
  turn. Never retroactive rewriting.
- `ask` must be actionable: the other agent must be able to start without asking
  you again. If you expect nothing (just an FYI), put `ask: —`.
- Keep a turn **bounded**: if it exceeds ~150 lines or several topics, split it
  into several successive turns (one topic = one turn).

---

## 4. Work cycle (each agent's loop)

```
loop:
  1. read LOCK (status / wait)
  2. if state == AWAITING_<me> or IDLE:
       a. CLAIM  : ./m8shift.py claim <me>   → state=WORKING_<ME>, expires=now+30min
                   EXCLUSIVE: if someone else has taken the pen in the meantime,
                   claim FAILS → go to 3.
       b. WORK in the repository (while you hold the pen, you alone)
       c. APPEND  : ./m8shift.py append <me> --to <other>
                   writes my turn <turn+1>, state=AWAITING_<OTHER>
  3. else (WORKING_<other> or AWAITING_<other>):
       wait ~60 s (wait), go back to 1
  4. if state == DONE: exit
```

In practice: `claim` **acquires** the pen (exclusive), `append` **closes** your
turn and hands off, `wait` waits for your turn. The explicit acquisition before
working is what guarantees that a single agent modifies the repository at a time.

> **Concurrency model (two levels)**:
> 1. **Transitions** serialized by an inter-process lock (`.m8shift.lock`,
>    `O_CREAT|O_EXCL`, with an ownership token): each read-modify-write of the
>    LOCK + atomic write (unique temporary + `os.replace`) is exclusive.
> 2. **Work window** protected by the persistent state `WORKING_<agent>`:
>    `claim` is the only acquisition, and it fails if someone else holds or has
>    already taken the pen. Two simultaneous `claim`s from `IDLE` ⇒ **only one
>    succeeds**; the other must wait. Since we work only after a successful
>    `claim`, two agents never modify the repository at the same time.
>
> An abandoned `.m8shift.lock` (killed process) is taken over after 60 s, token
> verified. *Limits*: the lock is **advisory** (a manual edit of `M8SHIFT.md`
> bypasses it); on a network FS (NFS) `O_EXCL`/`rename` are less reliable —
> cowork targets a repository on local disk. See also §0/§4 (mandatory claim).

---

## 5. Anti-deadlock (stale lock)

If the other agent crashes while holding the pen, the lock would stay stuck.
Guardrail:
- on CLAIM, we set `expires = now + 30 min`;
- if you see `state == WORKING_<other>` **and** `now > expires`, the lock is
  **stale**: take it over with `./m8shift.py claim <you> --force`, then open a
  turn noting the takeover (`done: takeover after stale lock from <other>`);
- **the tool enforces the rule**: `--force` is **refused** on a still-valid
  lock. You therefore cannot steal the pen from an active agent (this is
  intentional);
- you can **refresh your own** lock before it expires: `./m8shift.py claim
  <you>` when you already hold it resets `expires` to +30 min;
- `release` and `done` act only if **you** hold the pen (or if nobody holds it);
  `--force` overrides, reserved for recovery.

---

## 6. Keeping it bounded over time (bounded length)

`M8SHIFT.md` must not grow indefinitely:
- keep in `M8SHIFT.md` the `LOCK` block + the **~6 last turns**;
- `./m8shift.py archive --keep 6` moves the older turns (already closed) to
  `M8SHIFT.archive.md` (append), without ever touching the lock or the last open
  turn.
- The archive can be consulted but is **never** re-read by the loop: only the
  living part of `M8SHIFT.md` drives the relay.

---

## 7. The `m8shift.py` tool

```
./m8shift.py init [--name PROJECT] [--agents a,b] [--lang en|fr] [--force]  # (re)generates the kit here
./m8shift.py status                                # lock + last turn (NON-blocking)
./m8shift.py wait <agent> [--once] [--interval N]  # waits for your turn ; --once = 1 check (rc 3 if not your turn)
./m8shift.py claim <agent> [--force]               # ACQUIRE the pen (exclusive) — from your turn /
                                                  #   IDLE / your own lock ; --force = stale lock ONLY
./m8shift.py append <agent> --to <other> \
     --ask "..." --done "..." [--files a,b] [--body file.md|-]   # closes your turn + hands off
./m8shift.py release <agent> --to <other> [--force]  # hand off without a body (does NOT re-increment turn)
./m8shift.py done <agent> [--force]                 # close the session (state=DONE)
./m8shift.py archive [--keep N]                     # purge old closed turns (never turn #0)
```

- **`claim` first**: you must hold the pen (`WORKING_<you>`) to `append`.
  `claim` is **exclusive** (a single winner if two agents try together).
- `append` is accepted **only from `WORKING_<you>`**; it writes the turn and
  hands off. `--body -` reads the body from stdin; `--body f.md` from a file;
  without `--body`, the turn has only the header.
- `--to` must target **the other** agent (self-hand-off refused: strict alternation).
- **Non-blocking** inspection: `status` or `wait <you> --once`. `wait <you>`
  **without** `--once` blocks until your turn — do not use it if you must return
  control to your loop in the meantime.

---

## 8. Adoption by any project (portability)

`m8shift.py` is **self-sufficient**: it embeds this protocol, the `M8SHIFT.md`
template and the anchors. To adopt the relay in a project:

```bash
cp /path/to/m8shift.py .          # copy the only file needed
./m8shift.py init                 # project name = folder name (otherwise --name)
```

`init`:
- writes `M8SHIFT.protocol.md` (this document) and `M8SHIFT.md` (a fresh IDLE
  lock); `M8SHIFT.md` is **not** overwritten if it already exists (except with
  `--force`) → the state of the ongoing relay is preserved;
- injects at the **top** a "Co-work relay" block into **each active agent's anchor**
  (by default `CLAUDE.md` and `AGENTS.md`; created if missing), between
  `M8SHIFT:STANZA` markers → **idempotent** re-injection (moves/updates the block
  without duplicating, existing content preserved; the prior file is backed up to
  `<anchor>.cowork.bak`);
- if `CLAUDE.md` existed but no Codex instruction (`AGENTS.md` or
  `AGENTS.override.md`) existed, automatically creates in `AGENTS.md` a bridge
  asking Codex to read the shared instructions in `CLAUDE.md`. A pre-existing
  Codex anchor is never completed or replaced automatically;
- renames a single `claude.md`/`agents.md` variant to the canonical
  auto-loaded name, including on a case-insensitive FS. Several coexisting
  variants are refused rather than silently merged. If Git is available and the
  variant is tracked, it uses `git mv -f` to also update the index;
- if `AGENTS.override.md` exists, it also synchronizes the stanza there: Codex
  loads this override instead of `AGENTS.md` in the same folder.

### Bootstrap / uptake by the agents

cowork is **passive**: it never "calls" any AI. It relies on the convention of each
host tool — **Claude reads `CLAUDE.md`, Codex reads `AGENTS.md`**, and any other active
agent reads its own anchor — at session/execution startup. The bootstrap chain is
therefore:

```mermaid
flowchart LR
    I["m8shift.py init"] --> S["inject the stanza into<br/>each active agent's anchor"]
    S --> R["each agent reads its anchor<br/>at session start"]
    R --> L["applies M8SHIFT.protocol.md<br/>(the wait / claim / work / append loop)"]
```

- **After `init`**: start a new session/execution of the agent. A session
  already open has generally built its instruction chain before the injection.
- **Interactive Codex or `codex exec`**: `AGENTS.md` is loaded if the command
  starts from the project root or one of its subfolders. *Headless* mode is not
  in itself a limit; a cron/CI launched outside the project, however, does not
  discover the anchor.
- **Codex override**: `AGENTS.override.md` masks `AGENTS.md` in the same folder;
  `init` therefore injects the stanza into both when it is present.
- **Codex size**: Codex stacks the instruction files up to a *combined* ceiling
  (`project_doc_max_bytes`, 32 KiB by default) and truncates the file that
  overflows to the remaining byte count. Putting the stanza at the top thus
  keeps it in priority (and a file closer to the cwd takes precedence);
  nevertheless keep the anchors **lightweight**.
- **General limit**: cowork cannot force an AI to read anything. Without a
  project root/context, point the agent explicitly to `M8SHIFT.protocol.md`.

Codex reference: https://developers.openai.com/codex/guides/agents-md
"""

STANZA_EN = """{begin}
## Co-work relay — self-contained (no human explanation needed)

You are **{me}** in this project. As soon as a `M8SHIFT.md` is present at the root,
it is your source of coordination with **{other}**: apply `M8SHIFT.protocol.md`
(read it once, see its §0) BEFORE any other work. **You only work and write if
you have acquired the pen via `claim`.**

```bash
./m8shift.py status                # who holds the pen? (non-blocking)
./m8shift.py wait {me} --once      # rc 0 = you may acquire ; rc 3 = not yet
```

- **Acquire first** (`state == AWAITING_{ME}` or `IDLE`):
  `./m8shift.py claim {me}` — **exclusive**: if {other} has already taken the pen, it
  fails → go back to waiting. If it succeeds, you hold the pen (`WORKING_{ME}`).
- **Then work and close your turn**: read the `ask:` that {other} left you
  (at IDLE startup, nothing to honor), do the work, then:
  `./m8shift.py append {me} --to {other} --ask "…" --done "…" [--files a,b]`
- **Not your turn**: touch nothing; `./m8shift.py wait {me}` blocks until your
  turn (poll ~60 s), then retry `claim`.
- **{other}'s lock is stale** (`WORKING_{OTHER}` + `now > expires`):
  `./m8shift.py claim {me} --force`.

A closed turn is immutable: to react, open the next turn.

_Interactive-UI note_: in a chat UI (VS Code, …) a human resumes you between turns —
`wait` blocks a process, it does not wake your UI. Fully hands-off relays need a
headless runner.
{end}"""

COWORK_EN = r"""<!-- ╔════════════════════════════════════════════════════════════╗
     ║  M8Shift · single-file multi-agent relay · protocol v1     ║
     ║  Read M8SHIFT.protocol.md BEFORE writing here.             ║
     ╚════════════════════════════════════════════════════════════╝ -->

# M8Shift · __PROJECT__

> Shared work file. **Only one agent writes at a time.** The lock is the
> `LOCK` block below. Only write if `state == AWAITING_<you>`. Details →
> [M8SHIFT.protocol.md](M8SHIFT.protocol.md). Tool → `./m8shift.py status`.

<!-- M8SHIFT:LOCK:BEGIN -->
holder:   none
state:    IDLE
agents:   __AGENTS__
lang:     __LANG__
turn:     0
since:    __NOW__
expires:  -
note:     session initialized, no turn opened
<!-- M8SHIFT:LOCK:END -->

---

## Turn log

<!-- Turns stack below, from oldest to most recent.                          -->
<!-- Turn format: see M8SHIFT.protocol.md §3. Never edit a turn that is        -->
<!-- already closed (END set): add a new turn instead.                        -->

<!-- M8SHIFT:TURN 0 system BEGIN -->
- from:    system
- to:      none
- ask:     —
- done:    Relay initialization. The first agent that starts runs
           `./m8shift.py claim __A__` (or `__B__`), works, then
           `./m8shift.py append __A__ --to __B__ --ask "..." --done "..."`.
- files:   M8SHIFT.md, M8SHIFT.protocol.md, m8shift.py
- handoff: none
<!-- M8SHIFT:TURN 0 system END -->
"""

BRIDGE_EN = """## Shared project instructions

Read and fully apply `CLAUDE.md`, which contains the shared project instructions
for Claude and Codex.
"""

PROTOCOL = {"en": PROTOCOL_EN, "fr": PROTOCOL_FR}
STANZA = {"en": STANZA_EN, "fr": STANZA_FR}
COWORK_TPL = {"en": COWORK_EN, "fr": COWORK_FR}
BRIDGE = {"en": BRIDGE_EN, "fr": BRIDGE_FR}


# ----------------------------------------------------------------- i18n (en/fr)
# Resolved language: --lang (init) > $M8SHIFT_LANG ($COWORK_LANG deprecated fallback)
# > LOCK `lang` field > en.

def resolve_lang(explicit=None, lk=None):
    if explicit in LANGS:
        return explicit
    env = os.environ.get("M8SHIFT_LANG") or os.environ.get("COWORK_LANG", "")
    if env in LANGS:
        return env
    if lk and lk.get("lang") in LANGS:
        return lk["lang"]
    return DEFAULT_LANG


LANG = resolve_lang()  # baseline (refined by load_or_die / cmd_init)

MESSAGES = {
    "en": {
        "lock_busy": "internal lock busy (another m8shift.py is writing) — retry.",
        "cowork_missing": "M8SHIFT.md not found — run `./m8shift.py init` first.",
        "lock_missing": "{file} corrupted: LOCK block not found — `./m8shift.py init --force` to reset the lock.",
        "lock_invalid": "{file} corrupted (invalid LOCK: {errs}) — `./m8shift.py init --force` to repair.",
        "field_newline": "refused: {label} must not contain a line break.",
        "field_reserved": "refused: {label} contains a reserved marker ({marker}).",
        "bad_agent": "invalid agent: {a} (expected: {agents})",
        "bad_roster": "invalid --agents: {raw} — provide at least two distinct agent names (e.g. claude,codex).",
        "anchor_no_map": "{agent}: no known anchor file — bootstrap manually (point {agent} to M8SHIFT.protocol.md).",
        "anchor_collision": "{agent}: anchor {filename} is already used by another active agent — skipped (bootstrap {agent} manually).",
        "roster_extra": "{n} agents declared; only the first two relay in this version ({pair}). Extra names are reserved for the future N-agent mode.",
        "roster_conflict": "refused: --agents {requested} differs from the roster {existing} already declared — re-run with --force to reset it, or omit --agents to keep the current roster.",
        "anchor_ambiguous": "ambiguous anchors for {canonical}: {others} — consolidate them before `m8shift.py init`.",
        "anchor_git_fail": "could not rename {actual} via Git to {canonical}: {detail}",
        "git_unknown_err": "unknown git error",
        "migrated_git": "{actual} → {canonical}: renamed via Git for auto-loading",
        "migrated_fs": "{actual} → {canonical}: renamed for auto-loading",
        "stanza_incomplete": "{filename}: incomplete M8Shift stanza — fix the markers before init.",
        "stanza_updated": "stanza refreshed at top",
        "stanza_added": "stanza added at top",
        "file_created": "file created",
        "anchor_result": "{filename}: {action}",
        "proto_written": "{file}: written",
        "proto_uptodate": "{file}: already up to date",
        "cowork_preserved": "{file}: preserved (already exists; --force to reset)",
        "cowork_written": "{file}: written (project “{name}”, lock IDLE)",
        "bridge_added": "AGENTS.md: automatic bridge to the shared instructions in CLAUDE.md",
        "override_synced": "{filename}: Codex override active, stanza synced",
        "init_header": "✓ m8shift init — project “{name}” in {here}",
        "init_start": "Start: ./m8shift.py claim {a}  (then work, then ./m8shift.py append {a} --to {b} --ask \"…\" --done \"…\")",
        "init_bootstrap": "Bootstrap: start a new session/run of each agent to reload its anchor.",
        "status_stale": "  ⚠ stale lock — reclaim with: claim <you> --force",
        "last_turn": "── last turn: #{n} by {who}",
        "wait_your_turn": "✓ your turn ({st}) — `./m8shift.py claim {agent}` to acquire the pen.",
        "wait_free": "✓ free ({st}) — `./m8shift.py claim {agent}` to acquire the pen.",
        "wait_done": "session DONE — nothing to wait for.",
        "wait_stale": "⚠ {other}'s lock is stale — claim --force possible.",
        "wait_not_yet": "… not your turn: {st} (holder={holder}).",
        "wait_poll": "… {st} (holder={holder}), re-checking in {interval}s",
        "bad_interval": "--interval must be an integer >= 1.",
        "claim_active": "refused: {holder}'s lock is still valid (expires {expires}). --force only reclaims a stale lock (protocol §5).",
        "claim_refused": "refused: state={st}, holder={holder} — it is not your turn.",
        "note_reclaim": "reclaimed after {holder}'s stale lock",
        "note_holds": "{agent} holds the pen",
        "claim_ok": "✓ pen taken by {agent} (expires {expires}{suffix}).",
        "claim_reclaim_suffix": " — stale lock reclaimed",
        "body_error": "--body: {e}",
        "to_self_append": "refused: --to must target the other agent (strict alternation, protocol §1).",
        "append_need_claim": "refused: you do not hold the pen (state={st}) — run `./m8shift.py claim {agent}` first (exclusive acquisition), then append.",
        "note_turn": "turn {n} posted by {agent}, awaiting {to}",
        "append_ok": "✓ turn {n} written by {agent}, handed off to {to}.",
        "to_self": "refused: --to must target the other agent.",
        "not_holder_release": "refused: {holder} holds the pen, not you (--force to override).",
        "note_release": "handed off to {to} by {agent} (no turn)",
        "release_ok": "✓ handed off to {to}.",
        "not_holder_done": "refused: {holder} holds the pen, not you (--force to close anyway).",
        "note_done": "session closed by {agent}",
        "done_ok": "✓ session DONE.",
        "archive_none": "nothing to archive ({n} archivable turn(s), keep={keep}).",
        "archive_header": "# M8Shift · turn archive\n\n",
        "archive_ok": "✓ {n} turn(s) archived → {file} (kept: {keep}).",
        "recap_turns": "── last {n} turn(s) ──────────────────────",
        "peek_none": "(no handoff addressed to {agent} yet)",
        "migrate_ambiguous": "refused: both {old} and {new} exist — resolve the ambiguity (keep one) before migrating.",
        "migrate_busy": "refused: relay is mid-turn (state={state}) — finish or release the turn first.",
        "migrate_noop": "nothing to migrate — already on the M8Shift names.",
        "migrate_would": "would rename {old} → {new} (and rewrite COWORK:* markers to M8SHIFT:*)",
        "migrate_renamed": "{old} → {new} (markers rewritten to M8SHIFT:*)",
        "migrate_lock_removed": "removed stale .cowork.lock (a fresh .m8shift.lock is created on demand)",
        "migrate_anchor": "{filename}: stanza re-pointed to ./m8shift.py",
        "migrate_dry": "(dry-run) nothing written.",
        "migrate_done": "✓ migrated to the M8Shift names. cowork.py stays a deprecated shim; the old names remain readable.",
    },
    "fr": {
        "lock_busy": "verrou interne occupé (un autre m8shift.py écrit) — réessaie.",
        "cowork_missing": "M8SHIFT.md introuvable — lance d'abord `./m8shift.py init`.",
        "lock_missing": "{file} corrompu : bloc LOCK introuvable — `./m8shift.py init --force` pour réinitialiser le verrou.",
        "lock_invalid": "{file} corrompu (LOCK invalide : {errs}) — `./m8shift.py init --force` pour réparer.",
        "field_newline": "refus: {label} ne doit pas contenir de saut de ligne.",
        "field_reserved": "refus: {label} contient un marqueur réservé ({marker}).",
        "bad_agent": "agent invalide: {a} (attendu: {agents})",
        "bad_roster": "--agents invalide : {raw} — fournis au moins deux noms d'agents distincts (ex. claude,codex).",
        "anchor_no_map": "{agent} : aucun fichier d'ancrage connu — amorce manuellement (pointe {agent} vers M8SHIFT.protocol.md).",
        "anchor_collision": "{agent} : l'ancrage {filename} est déjà utilisé par un autre agent actif — ignoré (amorce {agent} manuellement).",
        "roster_extra": "{n} agents déclarés ; seuls les deux premiers font le relais dans cette version ({pair}). Les noms supplémentaires sont réservés au futur mode N agents.",
        "roster_conflict": "refus : --agents {requested} diffère du roster {existing} déjà déclaré — relance avec --force pour le réinitialiser, ou omets --agents pour conserver le roster courant.",
        "anchor_ambiguous": "ancrages ambigus pour {canonical}: {others} — consolide-les avant `m8shift.py init`.",
        "anchor_git_fail": "impossible de renommer {actual} via Git vers {canonical}: {detail}",
        "git_unknown_err": "erreur git inconnue",
        "migrated_git": "{actual} → {canonical}: renommé via Git pour auto-chargement",
        "migrated_fs": "{actual} → {canonical}: renommé pour auto-chargement",
        "stanza_incomplete": "{filename}: stanza M8Shift incomplète — répare les marqueurs avant init.",
        "stanza_updated": "stanza actualisée en tête",
        "stanza_added": "stanza ajoutée en tête",
        "file_created": "fichier créé",
        "anchor_result": "{filename}: {action}",
        "proto_written": "{file}: écrit",
        "proto_uptodate": "{file}: déjà à jour",
        "cowork_preserved": "{file}: préservé (existe déjà ; --force pour réinitialiser)",
        "cowork_written": "{file}: écrit (projet « {name} », verrou IDLE)",
        "bridge_added": "AGENTS.md: pont automatique vers les instructions communes de CLAUDE.md",
        "override_synced": "{filename}: override Codex actif, stanza synchronisée",
        "init_header": "✓ m8shift init — projet « {name} » dans {here}",
        "init_start": "Démarrer : ./m8shift.py claim {a}  (puis travaille, puis ./m8shift.py append {a} --to {b} --ask \"…\" --done \"…\")",
        "init_bootstrap": "Amorçage : démarre une nouvelle session/exécution de chaque agent pour recharger son ancrage.",
        "status_stale": "  ⚠ verrou PERIME — reprenable avec: claim <toi> --force",
        "last_turn": "── dernier tour: #{n} par {who}",
        "wait_your_turn": "✓ à toi ({st}) — `./m8shift.py claim {agent}` pour acquérir le stylo.",
        "wait_free": "✓ libre ({st}) — `./m8shift.py claim {agent}` pour acquérir le stylo.",
        "wait_done": "session DONE — rien a attendre.",
        "wait_stale": "⚠ verrou de {other} PERIME — claim --force possible.",
        "wait_not_yet": "… pas ton tour: {st} (holder={holder}).",
        "wait_poll": "… {st} (holder={holder}), nouvelle verif dans {interval}s",
        "bad_interval": "--interval doit être un entier >= 1.",
        "claim_active": "refus: verrou de {holder} encore valide (expire {expires}). --force ne reprend qu'un verrou périmé (protocole §5).",
        "claim_refused": "refus: state={st}, holder={holder} — ce n'est pas ton tour.",
        "note_reclaim": "reprise après lock périmé de {holder}",
        "note_holds": "{agent} tient le stylo",
        "claim_ok": "✓ verrou pris par {agent} (expire {expires}{suffix}).",
        "claim_reclaim_suffix": " — reprise lock périmé",
        "body_error": "--body: {e}",
        "to_self_append": "refus: --to doit viser l'autre agent (alternance stricte, protocole §1).",
        "append_need_claim": "refus: tu ne tiens pas le stylo (state={st}) — fais d'abord `./m8shift.py claim {agent}` (acquisition exclusive), puis append.",
        "note_turn": "tour {n} pose par {agent}, en attente de {to}",
        "append_ok": "✓ tour {n} ecrit par {agent}, main passee a {to}.",
        "to_self": "refus: --to doit viser l'autre agent.",
        "not_holder_release": "refus: {holder} tient le stylo, pas toi (--force pour outrepasser).",
        "note_release": "main passee a {to} par {agent} (sans tour)",
        "release_ok": "✓ main passee a {to}.",
        "not_holder_done": "refus: {holder} tient le stylo, pas toi (--force pour clore quand même).",
        "note_done": "session close par {agent}",
        "done_ok": "✓ session DONE.",
        "archive_none": "rien a archiver ({n} tour(s) archivable(s), keep={keep}).",
        "archive_header": "# M8Shift · archive des tours\n\n",
        "archive_ok": "✓ {n} tour(s) archive(s) → {file} (gardes: {keep}).",
        "recap_turns": "── {n} dernier(s) tour(s) ────────────────",
        "peek_none": "(aucune passation adressée à {agent} pour l'instant)",
        "migrate_ambiguous": "refus : {old} ET {new} existent — lève l'ambiguïté (garde-en un) avant de migrer.",
        "migrate_busy": "refus : relais en cours de tour (state={state}) — termine ou rends la main d'abord.",
        "migrate_noop": "rien à migrer — déjà sur les noms M8Shift.",
        "migrate_would": "renommerait {old} → {new} (et réécrirait les marqueurs COWORK:* en M8SHIFT:*)",
        "migrate_renamed": "{old} → {new} (marqueurs réécrits en M8SHIFT:*)",
        "migrate_lock_removed": "ancien .cowork.lock supprimé (un .m8shift.lock neuf est créé à la demande)",
        "migrate_anchor": "{filename} : stanza re-pointée vers ./m8shift.py",
        "migrate_dry": "(dry-run) rien écrit.",
        "migrate_done": "✓ migré vers les noms M8Shift. cowork.py reste un shim déprécié ; les anciens noms restent lisibles.",
    },
}


def tr(key, **kw):
    cat = MESSAGES.get(LANG, MESSAGES[DEFAULT_LANG])
    s = cat.get(key) or MESSAGES[DEFAULT_LANG].get(key, key)
    return s.format(**kw) if kw else s

def now():
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0)


def iso(t):
    return t.strftime("%Y-%m-%dT%H:%M:%SZ")


def parse_iso(s):
    s = (s or "").strip()
    if not s or s == "-":
        return None
    try:
        return dt.datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=dt.timezone.utc)
    except ValueError:
        return None


def read(path=COWORK):
    with open(path, encoding="utf-8") as f:
        return f.read()


def _current_umask():
    m = os.umask(0)
    os.umask(m)
    return m


def write(text, path=COWORK):
    """Atomic write: UNIQUE temporary file + os.replace, preserving the mode of the
    existing target file (mkstemp forces 0600 otherwise)."""
    d = os.path.dirname(path) or "."
    os.makedirs(d, exist_ok=True)  # nested anchors (e.g. .github/…) need their parent
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".m8shift-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        try:
            os.chmod(tmp, os.stat(path).st_mode)  # keep the existing mode
        except OSError:
            os.chmod(tmp, 0o666 & ~_current_umask())  # new file: usual mode
        os.replace(tmp, path)  # atomic replacement
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise


@contextlib.contextmanager
def file_lock(timeout=LOCK_TIMEOUT):
    """Inter-process lock via exclusive file creation (O_CREAT|O_EXCL).

    Serializes the LOCK read-modify-write: two concurrent `cowork.py` runs cannot
    mutate `COWORK.md` at the same time. The lock carries an **ownership token**: we
    only remove it (at the end of the section, or when taking over a lock abandoned
    for LOCK_STALE_S) after verifying the token, so we never erase a successor's
    lock.
    """
    token = f"{os.getpid()}:{time.time_ns()}".encode()
    start = time.monotonic()
    while True:
        try:
            fd = os.open(LOCKFILE, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            try:
                os.write(fd, token)
            finally:
                os.close(fd)
            break
        except FileExistsError:
            try:
                victim_age = time.time() - os.path.getmtime(LOCKFILE)
                if victim_age > LOCK_STALE_S:
                    with open(LOCKFILE, "rb") as f:
                        victim = f.read()
                    # still stale AND unchanged since the read → safe takeover
                    if time.time() - os.path.getmtime(LOCKFILE) > LOCK_STALE_S:
                        with open(LOCKFILE, "rb") as f2:
                            if f2.read() == victim:
                                os.unlink(LOCKFILE)
                                continue
            except OSError:
                pass
            if time.monotonic() - start > timeout:
                sys.exit(tr("lock_busy"))
            time.sleep(0.05)
    try:
        yield
    finally:
        # remove ONLY our own lock (token verified)
        try:
            with open(LOCKFILE, "rb") as f:
                mine = f.read() == token
            if mine:
                os.unlink(LOCKFILE)
        except OSError:
            pass


def require_cowork():
    if not os.path.exists(COWORK):
        sys.exit(tr("cowork_missing"))


def load_or_die():
    """Read the living relay file while validating the LOCK block (presence AND
    schema); clean exit otherwise — no invalid value must reach the logic (no
    traceback). Accepts either brand of LOCK markers (legacy CoWork or M8Shift)."""
    require_cowork()
    text = read()
    begin, end = lock_markers(text)
    if begin not in text or end not in text:
        sys.exit(tr("lock_missing", file=os.path.basename(COWORK)))
    lk = get_lock(text)
    globals()["LANG"] = resolve_lang(lk=lk)  # localize the validation errors below
    pair = active_pair(lk)
    errs = []
    if "agents" in lk:
        ag_valid, ag_invalid = roster_tokens(lk["agents"])
        if ag_invalid or len(ag_valid) < 2:  # reject a partially-invalid stored roster
            errs.append(f"agents={lk.get('agents')!r}")
    if lk.get("state") not in valid_states(pair):
        errs.append(f"state={lk.get('state')!r}")
    if not re.fullmatch(r"\d+", lk.get("turn", "")):
        errs.append(f"turn={lk.get('turn')!r}")
    if lk.get("holder") not in set(pair) | {"none"}:
        errs.append(f"holder={lk.get('holder')!r}")
    if lk.get("lang") not in (None, *LANGS):
        errs.append(f"lang={lk.get('lang')!r}")
    if errs:
        sys.exit(tr("lock_invalid", file=os.path.basename(COWORK), errs=", ".join(errs)))
    globals()["ROSTER"] = pair
    return text


def clean_field(label, val):
    """Single-line field: rejects line breaks and reserved markers (injection-safe)."""
    val = (val or "").strip()
    if "\n" in val or "\r" in val:
        sys.exit(tr("field_newline", label=label))
    for r in RESERVED:
        if r in val:
            sys.exit(tr("field_reserved", label=label, marker=r))
    return val


def clean_body(text):
    """Multi-line body: neutralizes any injected reserved marker (zero-width after the
    brand prefix), for BOTH brands, so it cannot masquerade as a real turn."""
    return text.replace("COWORK:", "COWORK\u200b:").replace("M8SHIFT:", "M8SHIFT\u200b:")


def lock_markers(text):
    """Return the (begin, end) LOCK markers present in `text`: the new (M8SHIFT) brand
    when present, else the old (COWORK) brand for legacy files, else the new brand.
    `set_lock` writes back the SAME pair so a session never converts a file's brand."""
    if LOCK_BEGIN in text:
        return LOCK_BEGIN, LOCK_END
    if OLD_LOCK_BEGIN in text:
        return OLD_LOCK_BEGIN, OLD_LOCK_END
    return LOCK_BEGIN, LOCK_END


def get_lock(text):
    begin, end = lock_markers(text)
    i = text.index(begin) + len(begin)
    j = text.index(end)
    fields = {}
    for line in text[i:j].splitlines():
        line = line.strip()
        m = re.match(r"([a-z_]+):\s*(.*)$", line)
        if m:
            fields[m.group(1)] = m.group(2).strip()
    return fields


def set_lock(text, fields):
    begin, end = lock_markers(text)  # preserve the brand already in the file
    i = text.index(begin) + len(begin)
    j = text.index(end)
    body = "\n" + "\n".join(
        f"{k}:{' ' * max(1, 9 - len(k))}{v}"
        for k, v in fields.items()
    ) + "\n"
    return text[:i] + body + text[j:]


def roster_tokens(raw):
    """Split a roster CSV into (valid, invalid). Valid = normalized AGENT_RE names
    (lowercased, de-duplicated, order kept); invalid = non-empty tokens that are not
    a well-formed agent name. Empty tokens (trailing comma) are ignored, not invalid."""
    valid, invalid = [], []
    for tok in (raw or "").split(","):
        s = tok.strip()
        if not s:
            continue
        n = s.lower()
        if re.fullmatch(AGENT_RE, n):
            if n not in valid:
                valid.append(n)
        else:
            invalid.append(s)
    return valid, invalid


def parse_roster_csv(raw):
    """Valid agents from a CSV (lenient: empty/invalid tokens are ignored)."""
    return roster_tokens(raw)[0]


def roster_full(lk):
    """Full declared roster (>=2 names); falls back to the default pair if absent/invalid."""
    names = parse_roster_csv(lk.get("agents", ""))
    return names if len(names) >= 2 else list(AGENTS)


def active_pair(lk):
    """ACTIVE pair for this version = the first 2 of the declared roster.
    (Names beyond the 2nd are kept but inactive until the N-agent mode.)"""
    return tuple(roster_full(lk)[:2])


def valid_states(pair):
    s = {"IDLE", "DONE"}
    for a in pair:
        s.add(f"WORKING_{a.upper()}")
        s.add(f"AWAITING_{a.upper()}")
    return s


def other(agent):
    for a in ROSTER:
        if a != agent:
            return a
    return agent


def need_agent(a):
    if a not in ROSTER:
        sys.exit(tr("bad_agent", a=repr(a), agents=" | ".join(ROSTER)))
    return a


# ---------------------------------------------------------------- init / anchors

def ensure_canonical_anchor(canonical, create=True):
    """Return an auto-loadable anchor, along with its migration action if any.

    A single variant (`agents.md`) is renamed to the canonical name (`AGENTS.md`).
    On a case-insensitive FS, a two-step rename also forces the case of the on-disk
    entry. Several coexisting variants are ambiguous: we refuse rather than merge or
    silently overwrite user content.
    """
    try:
        on_disk = os.listdir(HERE)
    except OSError:
        on_disk = []

    variants = [f for f in on_disk if f.casefold() == canonical.casefold()]
    if canonical in variants:
        if len(variants) > 1:
            others = ", ".join(repr(v) for v in variants if v != canonical)
            sys.exit(tr("anchor_ambiguous", canonical=repr(canonical), others=others))
        return canonical, ""
    if not variants:
        return (canonical, "") if create else (None, "")
    if len(variants) > 1:
        names = ", ".join(repr(v) for v in variants)
        sys.exit(tr("anchor_ambiguous", canonical=repr(canonical), others=names))

    actual = variants[0]
    actual_path = os.path.join(HERE, actual)
    canonical_path = os.path.join(HERE, canonical)

    # If the variant is tracked by Git, a plain rename on a case-insensitive FS does
    # not update the index (`git add -A` would then keep agents.md). `git mv -f`
    # makes the case change durable in future clones.
    try:
        tracked = subprocess.run(
            ["git", "-C", HERE, "ls-files", "--error-unmatch", "--", actual],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        ).returncode == 0
    except OSError:
        tracked = False
    if tracked:
        moved = subprocess.run(
            ["git", "-C", HERE, "mv", "-f", "--", actual, canonical],
            capture_output=True,
            text=True,
            check=False,
        )
        if moved.returncode != 0:
            detail = (moved.stderr or moved.stdout).strip()
            sys.exit(tr("anchor_git_fail", actual=repr(actual), canonical=repr(canonical),
                        detail=detail or tr("git_unknown_err")))
        return canonical, tr("migrated_git", actual=actual, canonical=canonical)

    try:
        same_file = os.path.exists(canonical_path) and os.path.samefile(actual_path, canonical_path)
    except OSError:
        same_file = False
    if same_file:
        # A rename that only changes case is unreliable across OSes/filesystems.
        # Freeing the name first via an intermediate forces the canonical entry.
        intermediate = os.path.join(
            HERE, f".m8shift-anchor-{os.getpid()}-{time.time_ns()}.tmp"
        )
        os.replace(actual_path, intermediate)
        try:
            os.replace(intermediate, canonical_path)
        except BaseException:
            with contextlib.suppress(OSError):
                os.replace(intermediate, actual_path)
            raise
    else:
        os.replace(actual_path, canonical_path)
    return canonical, tr("migrated_fs", actual=actual, canonical=canonical)


def stanza_for(me):
    o = other(me)
    return STANZA[LANG].format(
        begin=STANZA_BEGIN, end=STANZA_END,
        me=me, ME=me.upper(), other=o, OTHER=o.upper(),
    )


def anchor_exists(canonical):
    """Whether a case variant of an anchor already exists on disk."""
    try:
        return any(
            filename.casefold() == canonical.casefold()
            for filename in os.listdir(HERE)
        )
    except OSError:
        return False


def inject_anchor(filename, me, initial_content=""):
    path = os.path.join(HERE, filename)
    block = stanza_for(me)
    if os.path.exists(path):
        cur = read(path)
        # accept either brand of stanza markers (legacy COWORK or M8Shift)
        has_begin = STANZA_BEGIN in cur or OLD_STANZA_BEGIN in cur
        has_end = STANZA_END in cur or OLD_STANZA_END in cur
        if has_begin != has_end:
            sys.exit(tr("stanza_incomplete", filename=filename))
        if has_begin:
            # Remove any old stanza (EITHER brand), even one placed at the end of the
            # file. The current version is reinserted at the top to stay prioritized if
            # the host tool truncates a large instruction file.
            pat = re.compile(
                "(?:" + re.escape(STANZA_BEGIN) + "|" + re.escape(OLD_STANZA_BEGIN) + ")"
                + r".*?"
                + "(?:" + re.escape(STANZA_END) + "|" + re.escape(OLD_STANZA_END) + ")",
                re.DOTALL,
            )
            remainder = pat.sub("", cur).lstrip("\n")
            action = tr("stanza_updated")
        else:
            remainder = cur
            action = tr("stanza_added")
        new = block + "\n"
        if remainder:
            new += "\n" + remainder
        if new != cur:  # back up the pre-init content before modifying an existing anchor
            write(cur, path + ".m8shift.bak")
    else:
        # Deliberate choice (tested): the stanza is the FIRST thing in the file, even
        # a new one, to stay prioritized/untruncated — no H1 title above it.
        new = block + "\n"
        if initial_content:
            new += "\n" + initial_content.rstrip() + "\n"
        action = tr("file_created")
    write(new, path)
    return tr("anchor_result", filename=filename, action=action)


def cmd_init(args):
    globals()["LANG"] = resolve_lang(explicit=getattr(args, "lang", "") or None)
    name = args.name or os.path.basename(HERE) or "project"
    results = []

    # --- roster (RFC stage 1): validate the requested CSV up front (CLI level).
    # An explicit but malformed token is rejected, never silently dropped.
    req_valid, req_invalid = roster_tokens(getattr(args, "agents", "") or "")
    if getattr(args, "agents", "") and (req_invalid or len(req_valid) < 2):
        sys.exit(tr("bad_roster", raw=repr(args.agents)))

    with file_lock():
        # Determine the ACTIVE pair UNDER the lock, so two concurrent inits cannot
        # compute different rosters before serializing. Pair = the first 2 declared
        # names; extras are stored but inactive until the N-agent mode.
        cowork_exists = os.path.exists(COWORK)
        existing = None
        if cowork_exists:
            try:
                existing_lk = get_lock(read(COWORK))
            except (OSError, ValueError):
                existing_lk = None
            if existing_lk is not None:
                # A preserved COWORK.md (no --force) must carry a VALID roster — don't
                # silently keep a corrupt one; point to --force to repair / re-seed.
                if not args.force and "agents" in existing_lk:
                    ev, einv = roster_tokens(existing_lk["agents"])
                    if einv or len(ev) < 2:
                        sys.exit(tr("lock_invalid", file=os.path.basename(COWORK), errs=f"agents={existing_lk['agents']!r}"))
                existing = roster_full(existing_lk)
        if req_valid and cowork_exists and not args.force:
            # COWORK.md is preserved (no --force): --agents must match the in-place
            # roster, else demand --force rather than silently ignoring it.
            if existing is not None and req_valid != existing:
                sys.exit(tr("roster_conflict", requested=",".join(req_valid),
                            existing=",".join(existing)))
            full = existing or req_valid
        elif req_valid and ((not cowork_exists) or args.force):
            full = req_valid
        elif cowork_exists and existing is not None:
            full = existing
        else:
            full = list(AGENTS)
        pair = tuple(full[:2])
        extra = full[2:]
        globals()["ROSTER"] = pair

        # Capture the state BEFORE creating the anchors. The CLAUDE → Codex bridge
        # must only be offered when a project genuinely had Claude instructions but
        # no Codex instructions.
        had_claude_anchor = anchor_exists(CLAUDE_ANCHOR)
        had_codex_anchor = (
            anchor_exists(CODEX_ANCHOR) or anchor_exists(CODEX_OVERRIDE)
        )

        # protocol: canonical source, (re)written only if missing or different
        if not os.path.exists(PROTO) or read(PROTO) != PROTOCOL[LANG]:
            write(PROTOCOL[LANG], PROTO)
            results.append(tr("proto_written", file=os.path.basename(PROTO)))
        else:
            results.append(tr("proto_uptodate", file=os.path.basename(PROTO)))

        # cowork.md: preserved if it exists (state of the ongoing relay), unless --force
        if os.path.exists(COWORK) and not args.force:
            results.append(tr("cowork_preserved", file=os.path.basename(COWORK)))
        else:
            text = (COWORK_TPL[LANG].replace("__PROJECT__", name)
                    .replace("__NOW__", iso(now())).replace("__LANG__", LANG)
                    .replace("__AGENTS__", ",".join(full))
                    .replace("__A__", pair[0]).replace("__B__", pair[1]))
            write(text, COWORK)
            results.append(tr("cowork_written", file=os.path.basename(COWORK), name=name))

        # Anchors: the stanza is injected for EACH agent of the active pair.
        # claude / codex keep their dedicated handling (CLAUDE → Codex bridge,
        # AGENTS.override.md sync). Any other roster agent gets a best-effort anchor
        # via the ANCHORS table (warning if it is unmapped or if its anchor file is
        # already taken by another active agent).
        injected = set()
        for ag in pair:
            if ag == "claude":
                claude_anchor, migration = ensure_canonical_anchor(CLAUDE_ANCHOR)
                if claude_anchor in injected:
                    results.append(tr("anchor_collision", agent=ag, filename=claude_anchor))
                    continue
                if migration:
                    results.append(migration)
                results.append(inject_anchor(claude_anchor, "claude"))
                injected.add(claude_anchor)
            elif ag == "codex":
                codex_anchor, migration = ensure_canonical_anchor(CODEX_ANCHOR)
                if codex_anchor in injected:
                    results.append(tr("anchor_collision", agent=ag, filename=codex_anchor))
                    continue
                if migration:
                    results.append(migration)
                # AGENTS.override.md masks AGENTS.md in Codex: if it exists, we inject
                # into both so the stanza survives its later removal.
                codex_initial_content = (
                    BRIDGE[LANG]
                    if had_claude_anchor and not had_codex_anchor and "claude" in pair
                    else ""
                )
                results.append(inject_anchor(
                    codex_anchor, "codex", initial_content=codex_initial_content
                ))
                injected.add(codex_anchor)
                if codex_initial_content:
                    results.append(tr("bridge_added"))

                codex_override, migration = ensure_canonical_anchor(CODEX_OVERRIDE, create=False)
                if migration:
                    results.append(migration)
                if codex_override:
                    results.append(inject_anchor(codex_override, "codex"))
                    results.append(tr("override_synced", filename=codex_override))
            else:
                anchor = ANCHORS.get(ag)
                if not anchor:
                    results.append(tr("anchor_no_map", agent=ag))
                    continue
                resolved, migration = ensure_canonical_anchor(anchor)
                if resolved in injected:
                    results.append(tr("anchor_collision", agent=ag, filename=resolved))
                    continue
                if migration:
                    results.append(migration)
                results.append(inject_anchor(resolved, ag))
                injected.add(resolved)

        if extra:
            results.append(tr("roster_extra", n=len(full), pair=",".join(pair)))

    print(tr("init_header", name=name, here=HERE))
    for r in results:
        print(f"  • {r}")
    print(tr("init_start", a=pair[0], b=pair[1]))
    print(tr("init_bootstrap"))
    return 0


# ---------------------------------------------------------------- relay commands

TURN_RE = re.compile(
    r"<!-- (?:COWORK|M8SHIFT):TURN (\d+) ([a-z][a-z0-9_-]*) BEGIN -->\n?"
    r"(.*?)"
    r"<!-- (?:COWORK|M8SHIFT):TURN \1 \2 END -->",
    re.DOTALL,
)


def parse_turns(text):
    """Read-only shared parser for the turn journal → [{n, agent, fields, body}].
    Leading `- key: value` lines become `fields` (key grammar [a-z_]+; UNKNOWN keys are
    kept verbatim, never silently dropped); everything after the first non-field line is
    the free-text `body`. Used by peek/recap/log; never feeds coordination logic."""
    out = []
    for m in TURN_RE.finditer(text):
        lines = m.group(3).splitlines()
        fields, i = {}, 0
        while i < len(lines):
            fm = re.match(r"- ([a-z_]+):\s*(.*)$", lines[i])
            if not fm:
                break
            fields[fm.group(1)] = fm.group(2).rstrip()
            i += 1
        out.append({
            "n": int(m.group(1)), "agent": m.group(2),
            "fields": fields, "body": "\n".join(lines[i:]).strip(),
        })
    return out


def cmd_recap(args):
    """Read-only session-start briefing: current LOCK + the last N turn summaries."""
    text = load_or_die()
    lk = get_lock(text)
    print("── LOCK ───────────────────────────────")
    for k in ("holder", "state", "agents", "turn", "since", "expires", "note"):
        v = ",".join(active_pair(lk)) if k == "agents" else lk.get(k, "")
        print(f"  {k:<8} {v}")
    turns = parse_turns(text)
    recent = turns[-args.turns:] if args.turns > 0 else turns
    if recent:
        print(tr("recap_turns", n=len(recent)))
        for t in recent:
            f = t["fields"]
            print(f"  #{t['n']} {f.get('from', t['agent'])} -> {f.get('to', '-')}: {f.get('done', '-')}")
    return 0


def cmd_peek(args):
    """Print the last handoff addressed to <agent> as parse-free key=value (+ body).
    rc 0 if it is your turn / free / done, rc 3 otherwise (mirrors `wait --once`)."""
    text = load_or_die()
    agent = need_agent(args.agent)
    st = get_lock(text).get("state", "")
    mine = [t for t in parse_turns(text) if t["fields"].get("to") == agent]
    if mine:
        t = mine[-1]
        for k, v in t["fields"].items():
            print(f"{k}={v}")
        if t["body"]:
            print()
            print(t["body"])
    else:
        print(tr("peek_none", agent=agent))
    return 0 if st in (f"AWAITING_{agent.upper()}", "IDLE", "DONE") else 3


def cmd_log(args):
    """Read-only relay timeline: one line per turn (chronological)."""
    text = load_or_die()
    turns = parse_turns(text)
    if args.all and os.path.exists(ARCHIVE):
        turns = parse_turns(read(ARCHIVE)) + turns
    turns.sort(key=lambda t: t["n"])
    if args.limit > 0:
        turns = turns[-args.limit:]
    for t in turns:
        f = t["fields"]
        frm, to = f.get("from", t["agent"]), f.get("to", "-")
        if args.oneline:
            print(f"#{t['n']} {frm} -> {to}  {f.get('done', '-')}")
        else:
            files = f.get("files", "-")
            nf = 0 if files in ("-", "") else len([x for x in files.split(",") if x.strip()])
            print(f"#{t['n']:<3} {frm:>8} -> {to:<8} ({nf} files)  done: {f.get('done', '-')}")
    return 0



def cmd_status(args):
    text = load_or_die()
    lk = get_lock(text)
    exp = parse_iso(lk.get("expires"))
    stale = (
        lk.get("state", "").startswith("WORKING_")
        and exp is not None
        and now() > exp
    )
    turns = re.findall(r"(?:COWORK|M8SHIFT):TURN (\d+) ([a-z][a-z0-9_-]*) BEGIN", text)
    last = {"n": int(turns[-1][0]), "agent": turns[-1][1]} if turns else None
    if getattr(args, "json", False):
        out = dict(lk)                       # raw LOCK fields…
        out["agents_active"] = active_pair(lk)   # …plus computed extras
        out["stale"] = stale
        out["last_turn"] = last
        print(json.dumps(out, ensure_ascii=False, sort_keys=True))
        return 0
    print("── LOCK ───────────────────────────────")
    for k in ("holder", "state", "lang", "turn", "since", "expires", "note"):
        print(f"  {k:<8} {lk.get(k, '')}")
        if k == "state":
            print(f"  {'agents':<8} {','.join(active_pair(lk))}")
    if stale:
        print(tr("status_stale"))
    if last:
        print(tr("last_turn", n=last["n"], who=last["agent"]))
    return 0


def cmd_wait(args):
    if not args.once and args.interval < 1:
        sys.exit(tr("bad_interval"))
    while True:
        text = load_or_die()              # sets ROSTER/LANG from the current file
        agent = need_agent(args.agent)    # validated against the current roster
        lk = get_lock(text)
        st = lk.get("state", "")
        target = f"AWAITING_{agent.upper()}"
        if st in (target, "IDLE"):
            key = "wait_your_turn" if st == target else "wait_free"
            print(tr(key, st=st, agent=agent))
            return 0
        if st == "DONE":
            print(tr("wait_done"))
            return 0
        exp = parse_iso(lk.get("expires"))
        if st == f"WORKING_{other(agent).upper()}" and exp and now() > exp:
            print(tr("wait_stale", other=other(agent)))
            return 0
        if args.once:  # single, non-blocking poll: rc=3 = not (yet) your turn
            print(tr("wait_not_yet", st=st, holder=lk.get("holder")))
            return 3
        print(tr("wait_poll", st=st, holder=lk.get("holder"), interval=args.interval))
        time.sleep(args.interval)


def cmd_claim(args):
    with file_lock():
        text = load_or_die()             # sets ROSTER/LANG from the on-disk file…
        agent = need_agent(args.agent)   # …so the agent is validated against it
        lk = get_lock(text)
        st = lk.get("state", "")
        holder = lk.get("holder", "none")
        exp = parse_iso(lk.get("expires"))
        stale = st.startswith("WORKING_") and exp is not None and now() > exp
        # your turn / IDLE / your own lock (TTL refresh); --force ONLY if stale.
        mine = st in ("IDLE", f"AWAITING_{agent.upper()}", f"WORKING_{agent.upper()}")
        if not (mine or (args.force and stale)):
            if args.force and st.startswith("WORKING_"):
                sys.exit(tr("claim_active", holder=holder, expires=lk.get("expires")))
            sys.exit(tr("claim_refused", st=st, holder=holder))
        reclaim = args.force and stale and holder not in (agent, "none")
        t = now()
        lk.update(
            holder=agent,
            state=f"WORKING_{agent.upper()}",
            since=iso(t),
            expires=iso(t + dt.timedelta(minutes=TTL_MIN)),
            note=(tr("note_reclaim", holder=holder) if reclaim
                  else tr("note_holds", agent=agent)),
        )
        write(set_lock(text, lk))
    suffix = tr("claim_reclaim_suffix") if reclaim else ""
    print(tr("claim_ok", agent=agent, expires=lk["expires"], suffix=suffix))
    return 0


def _read_body(spec):
    if not spec:
        return ""
    if spec == "-":
        return sys.stdin.read().rstrip("\n")
    try:
        with open(spec, encoding="utf-8") as f:
            return f.read().rstrip("\n")
    except OSError as e:
        sys.exit(tr("body_error", e=e))


def cmd_append(args):
    # Field/body reading stays OUTSIDE the critical section (stdin may block); agent
    # validation happens UNDER the lock, against the roster load_or_die reads.
    ask = clean_field("--ask", args.ask) or "—"
    done = clean_field("--done", args.done) or "—"
    files = clean_field("--files", args.files) or "—"
    body = clean_body(_read_body(args.body))

    with file_lock():
        text = load_or_die()
        agent = need_agent(args.agent)
        to = need_agent(args.to)
        if to == agent:
            sys.exit(tr("to_self_append"))
        lk = get_lock(text)
        st = lk.get("state", "")
        # append is allowed ONLY if you already hold the pen (prior exclusive claim).
        # This is what guarantees exclusivity of the WORK WINDOW, not just of the
        # journal write: you cannot work+append from IDLE.
        if st != f"WORKING_{agent.upper()}":
            sys.exit(tr("append_need_claim", st=st, agent=agent))
        n = int(lk.get("turn", "0")) + 1
        # Emit the brand already in this file (legacy COWORK files keep COWORK:TURN;
        # fresh M8Shift files get M8SHIFT:TURN). Never convert a file's brand here.
        brand = "M8SHIFT" if lock_markers(text)[0] == LOCK_BEGIN else "COWORK"
        block = (
            f"<!-- {brand}:TURN {n} {agent} BEGIN -->\n"
            f"- from:    {agent}\n"
            f"- to:      {to}\n"
            f"- ask:     {ask}\n"
            f"- done:    {done}\n"
            f"- files:   {files}\n"
            f"- handoff: {to}\n"
        )
        if body:
            block += "\n" + body + "\n"
        block += f"<!-- {brand}:TURN {n} {agent} END -->\n"

        # insert the turn at the end of the file (append-only journal)
        text = text.rstrip("\n") + "\n\n" + block

        t = now()
        lk.update(
            holder=to,
            state=f"AWAITING_{to.upper()}",
            turn=str(n),
            since=iso(t),
            expires="-",
            note=tr("note_turn", n=n, agent=agent, to=to),
        )
        write(set_lock(text, lk))
    print(tr("append_ok", n=n, agent=agent, to=to))
    return 0


def cmd_release(args):
    with file_lock():
        text = load_or_die()
        agent = need_agent(args.agent)
        to = need_agent(args.to)
        if to == agent:
            sys.exit(tr("to_self"))
        lk = get_lock(text)
        holder = lk.get("holder", "none")
        if holder not in (agent, "none") and not args.force:
            sys.exit(tr("not_holder_release", holder=holder))
        t = now()
        lk.update(
            holder=to, state=f"AWAITING_{to.upper()}",
            since=iso(t), expires="-",
            note=tr("note_release", to=to, agent=agent),
        )
        write(set_lock(text, lk))
    print(tr("release_ok", to=to))
    return 0


def cmd_done(args):
    with file_lock():
        text = load_or_die()
        agent = need_agent(args.agent)
        lk = get_lock(text)
        holder = lk.get("holder", "none")
        if holder not in (agent, "none") and not args.force:
            sys.exit(tr("not_holder_done", holder=holder))
        t = now()
        lk.update(holder="none", state="DONE", since=iso(t), expires="-",
                  note=tr("note_done", agent=agent))
        write(set_lock(text, lk))
    print(tr("done_ok"))
    return 0


def cmd_archive(args):
    pat = re.compile(
        r"<!-- (?:COWORK|M8SHIFT):TURN (\d+) ([a-z][a-z0-9_-]*) BEGIN -->.*?<!-- (?:COWORK|M8SHIFT):TURN \1 \2 END -->\n?",
        re.DOTALL,
    )
    keep = max(0, args.keep)
    with file_lock():
        text = load_or_die()
        # the bootstrap turn #0 (system) always stays in the living file
        matches = [m for m in pat.finditer(text) if m.group(1) != "0"]
        if len(matches) <= keep:
            print(tr("archive_none", n=len(matches), keep=keep))
            return 0
        to_move = matches[:-keep] if keep else matches
        moved = "".join(m.group(0) for m in to_move)
        # remove from the living file (last to first to keep offsets valid)
        for m in reversed(to_move):
            text = text[:m.start()] + text[m.end():]
        text = re.sub(r"\n{3,}", "\n\n", text)
        prev = read(ARCHIVE) if os.path.exists(ARCHIVE) else tr("archive_header")
        write(prev + moved, ARCHIVE)  # atomic write (tmp + os.replace)
        write(text)
    print(tr("archive_ok", n=len(to_move), file=os.path.basename(ARCHIVE), keep=keep))
    return 0


def _tracked(name):
    """True if `name` is tracked by Git in HERE (so a rename goes through `git mv`)."""
    try:
        return subprocess.run(
            ["git", "-C", HERE, "ls-files", "--error-unmatch", "--", name],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False,
        ).returncode == 0
    except OSError:
        return False


def _rename(old, new):
    """Rename old->new: via `git mv` when tracked (history follows), else os.replace."""
    op, npth = os.path.join(HERE, old), os.path.join(HERE, new)
    if _tracked(old):
        r = subprocess.run(["git", "-C", HERE, "mv", "-f", "--", old, new],
                           capture_output=True, text=True, check=False)
        if r.returncode == 0:
            return
    os.replace(op, npth)


def rebrand_living(text):
    """Make a legacy living file M8Shift-native: rewrite the structural HTML-comment
    markers everywhere (clean_body guarantees no stray 'COWORK:' in turn bodies) and the
    file/command references in the NON-turn header. Closed-turn bodies and the
    alignment-sensitive banner box are left verbatim (turn immutability)."""
    text = text.replace("COWORK:", "M8SHIFT:")
    begin, _ = lock_markers(text)
    idx = text.find(begin)
    if idx > 0:
        head, rest = text[:idx], text[idx:]
        out = []
        for ln in head.split("\n"):
            if "║" not in ln and "╔" not in ln and "╚" not in ln:
                ln = (ln.replace("COWORK.protocol.md", "M8SHIFT.protocol.md")
                        .replace("COWORK.archive.md", "M8SHIFT.archive.md")
                        .replace("COWORK.md", "M8SHIFT.md")
                        .replace("cowork.py", "m8shift.py")
                        .replace(".cowork.lock", ".m8shift.lock"))
                ln = re.sub(r"COWORK(?![_0-9A-Za-z:])", "M8Shift", ln)
            out.append(ln)
        text = "\n".join(out) + rest
    return text


def cmd_migrate_brand(args):
    """Opt-in: rename a legacy project's CoWork-named files to the M8Shift names and
    rewrite the structural markers. The ONLY command that converts a file's brand."""
    dry, backup = args.dry_run, not args.no_backup
    pairs = [("COWORK.md", "M8SHIFT.md"),
             ("COWORK.protocol.md", "M8SHIFT.protocol.md"),
             ("COWORK.archive.md", "M8SHIFT.archive.md")]
    with file_lock():
        for old, new in pairs:
            if os.path.exists(os.path.join(HERE, old)) and os.path.exists(os.path.join(HERE, new)):
                sys.exit(tr("migrate_ambiguous", old=old, new=new))
        living_old = os.path.join(HERE, "COWORK.md")
        if os.path.exists(living_old):
            lk0 = get_lock(read(living_old))
            if (lk0.get("state") or "").startswith("WORKING_"):
                sys.exit(tr("migrate_busy", state=lk0.get("state")))
        todo = [(o, n) for o, n in pairs if os.path.exists(os.path.join(HERE, o))]
        # NB: .cowork.lock is the EPHEMERAL inter-process lock (created/removed by
        # file_lock), not a persistent project file — nothing to migrate there; future
        # runs simply create .m8shift.lock.
        if not todo:
            print(tr("migrate_noop"))
            return 0
        out = []
        for old, new in todo:
            op = os.path.join(HERE, old)
            content = read(op)
            content = rebrand_living(content) if old == "COWORK.md" else content.replace("COWORK:", "M8SHIFT:")
            if dry:
                out.append(tr("migrate_would", old=old, new=new))
                continue
            if backup:
                write(read(op), op + ".m8shift.bak")
            _rename(old, new)
            write(content, os.path.join(HERE, new))
            out.append(tr("migrate_renamed", old=old, new=new))
        living_new = os.path.join(HERE, "M8SHIFT.md")
        if not dry and os.path.exists(living_new):
            lk = get_lock(read(living_new))
            pair = active_pair(lk)
            globals()["ROSTER"] = tuple(pair)
            globals()["LANG"] = resolve_lang(lk=lk)
            seen = set()
            targets = [(a, ANCHORS.get(a)) for a in pair]
            targets.append((pair[1] if len(pair) > 1 else pair[0], CODEX_OVERRIDE))
            for me, fn in targets:
                if not fn or fn in seen or not os.path.exists(os.path.join(HERE, fn)):
                    continue
                seen.add(fn)
                inject_anchor(fn, me)
                out.append(tr("migrate_anchor", filename=fn))
        for line in out:
            print(line)
        print(tr("migrate_dry") if dry else tr("migrate_done"))
    return 0



def main():
    # prog follows the invoked name so help reads `m8shift.py …` or, via the legacy
    # shim, `cowork.py …`.
    p = argparse.ArgumentParser(
        prog=os.path.basename(sys.argv[0]),
        description="Single-file multi-agent relay (M8Shift), portable.")
    sub = p.add_subparsers(dest="cmd", required=True)

    i = sub.add_parser("init", help="(re)generate the kit in this folder")
    i.add_argument("--name", default="")
    i.add_argument("--agents", default="",
                   help="comma-separated agent roster; the first two relay "
                        "(e.g. claude,codex). Extra names are reserved for the "
                        "future N-agent mode.")
    i.add_argument("--lang", choices=LANGS, default="",
                   help="language of generated files (default: en, or $M8SHIFT_LANG)")
    i.add_argument("--force", action="store_true", help="also reset the relay file")
    i.set_defaults(fn=cmd_init)

    st = sub.add_parser("status")
    st.add_argument("--json", action="store_true", help="machine-readable status (stdlib json)")
    st.set_defaults(fn=cmd_status)

    rc = sub.add_parser("recap", help="read-only briefing: LOCK + last N turns")
    rc.add_argument("--turns", type=int, default=6)
    rc.set_defaults(fn=cmd_recap)

    pk = sub.add_parser("peek", help="last handoff addressed to <agent> (rc 3 if not your turn)")
    pk.add_argument("agent")
    pk.set_defaults(fn=cmd_peek)

    lg = sub.add_parser("log", help="read-only relay timeline")
    lg.add_argument("--limit", type=int, default=0, help="show only the last N turns")
    lg.add_argument("--all", action="store_true", help="include archived turns")
    lg.add_argument("--oneline", action="store_true")
    lg.set_defaults(fn=cmd_log)

    w = sub.add_parser("wait")
    w.add_argument("agent")
    w.add_argument("--interval", type=int, default=60)
    w.add_argument("--once", action="store_true", help="check once and exit (rc 3 if not your turn)")
    w.set_defaults(fn=cmd_wait)

    c = sub.add_parser("claim")
    c.add_argument("agent")
    c.add_argument("--force", action="store_true")
    c.set_defaults(fn=cmd_claim)

    a = sub.add_parser("append")  # requires WORKING_<agent>: run `claim` first
    a.add_argument("agent")
    a.add_argument("--to", required=True)
    a.add_argument("--ask", default="")
    a.add_argument("--done", default="")
    a.add_argument("--files", default="")
    a.add_argument("--body", default="")
    a.set_defaults(fn=cmd_append)

    r = sub.add_parser("release")
    r.add_argument("agent")
    r.add_argument("--to", required=True)
    r.add_argument("--force", action="store_true")
    r.set_defaults(fn=cmd_release)

    d = sub.add_parser("done")
    d.add_argument("agent")
    d.add_argument("--force", action="store_true")
    d.set_defaults(fn=cmd_done)

    ar = sub.add_parser("archive")
    ar.add_argument("--keep", type=int, default=6)
    ar.set_defaults(fn=cmd_archive)

    mb = sub.add_parser("migrate-brand",
                        help="rename this project's CoWork-named files to the M8Shift names")
    mb.add_argument("--dry-run", action="store_true",
                    help="show what would change; write nothing")
    mb.add_argument("--no-backup", action="store_true",
                    help="do not write <file>.m8shift.bak backups")
    mb.set_defaults(fn=cmd_migrate_brand)

    args = p.parse_args()
    # ROSTER/LANG are resolved per command by load_or_die (and by cmd_init), under
    # the file lock, so agent validation always matches the on-disk roster.
    sys.exit(args.fn(args))


if __name__ == "__main__":
    main()
