#!/usr/bin/env python3
"""m8shift.py — single-file multi-agent relay (M8Shift), portable to any project.

Model: copy THIS single file to the root of a project, then `./m8shift.py init`.
`init` (re)generates M8SHIFT.md + M8SHIFT.protocol.md and injects the anchors into
CLAUDE.md / AGENTS.md. The lock (mutex) is the LOCK block at the top of M8SHIFT.md,
delimited by the HTML comments M8SHIFT:LOCK:BEGIN / M8SHIFT:LOCK:END. Turns are
delimited by M8SHIFT:TURN <n> <agent> BEGIN / END. See M8SHIFT.protocol.md.

(M8Shift was formerly named CoWork; since v3.0.0 the tool is M8Shift-only.)

No API key, no network, no daemon: a passive local CLI the agents drive with shell
commands; they bring their own auth, so M8Shift adds zero credentials.
"""
import argparse
import contextlib
import datetime as dt
import json
import os
import re
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
# Persistent file names (M8Shift-only; the living-file path keeps the internal name COWORK).
COWORK = os.path.join(HERE, "M8SHIFT.md")            # the living relay file
ARCHIVE = os.path.join(HERE, "M8SHIFT.archive.md")
PROTO = os.path.join(HERE, "M8SHIFT.protocol.md")
MEMORY = os.path.join(HERE, "M8SHIFT.memory.md")     # shared, append-only, human-curated notes
TASKS = os.path.join(HERE, "M8SHIFT.tasks.md")       # shared, append-only to-do event log
LOCKFILE = os.path.join(HERE, ".m8shift.lock")       # inter-process lock (O_EXCL)
LOCK_TIMEOUT = 10        # s: max wait to acquire the internal lock
LOCK_STALE_S = 60        # s: beyond this, a lock file is deemed abandoned
TTL_MIN = 30
DEFAULT_LANG = "en"              # default / ultimate fallback language
# Well-formed language tags M8Shift recognizes — a curated SUPERSET of LANGS. The LOCK `lang`
# field is validated against THIS (not the build-local LANGS), so a file written by a build that
# bundles more languages stays loadable here; an unbuilt language just downgrades to DEFAULT_LANG.
KNOWN_LANGS = ("en", "fr", "es", "it", "de", "pt", "ja", "ru", "zh-cn")
AGENTS = ("claude", "codex")     # default active pair
ROSTER = AGENTS                  # current ACTIVE roster (>=2 agents) — refined at runtime
AGENT_RE = r"[a-z][a-z0-9_-]*"   # normalized agent name (ASCII)
FIELD_KEY_RE = re.compile(r"[a-z][a-z0-9_]*\Z")   # advisory turn-field key: snake_case / x_*
# Turn fields the engine writes itself (routing) — an advisory field may not shadow them.
ENGINE_FIELDS = frozenset(("from", "to", "ask", "done", "files", "handoff"))
# Reserved marker prefixes: forbidden in fields, neutralized in bodies.
RESERVED = ("M8SHIFT:TURN", "M8SHIFT:LOCK", "M8SHIFT:STANZA", "M8SHIFT:TASK")
# Every char str.splitlines() treats as a line boundary — a single-line field must contain
# NONE of them, else a value could forge an extra `- key: value` line that parse_turns reads.
LINE_BREAKS = "\n\r\v\f\x1c\x1d\x1e\x85\u2028\u2029"   # all str.splitlines() boundaries

LOCK_BEGIN = "<!-- M8SHIFT:LOCK:BEGIN -->"
LOCK_END = "<!-- M8SHIFT:LOCK:END -->"
STANZA_BEGIN = "<!-- M8SHIFT:STANZA:BEGIN (generated by m8shift.py init - do not edit by hand) -->"
STANZA_END = "<!-- M8SHIFT:STANZA:END -->"

# Canonical names auto-loaded by the host tools. Existing variants are renamed to
# these names during `init`, including via a two-step rename on case-insensitive
# filesystems.
CLAUDE_ANCHOR = "CLAUDE.md"
CODEX_ANCHOR = "AGENTS.md"
CODEX_OVERRIDE = "AGENTS.override.md"

# Anchor file auto-loaded by each known agent. Best-effort: an agent missing from
# the table gets a manual-bootstrap warning (cf. RFC roster §5).
ANCHORS = {
    "claude": "CLAUDE.md",
    "codex": "AGENTS.md",
    "gemini": "GEMINI.md",
    "lechat": "AGENTS.md",   # Le Chat / Mistral: best-effort (convention unconfirmed)
    "mistral": "AGENTS.md",
    # NOTE: nested-path anchors (e.g. GitHub Copilot's .github/copilot-instructions.md)
    # are out of stage 1 — ensure_canonical_anchor is not path-aware (no case handling
    # in subdirs). Such an agent falls back to a manual-bootstrap warning.
}

# ----------------------------------------------------------------- templates

# ------------------------------------------------------------------- helpers

PROTOCOL_EN = r"""# M8Shift · Single-file relay protocol (v1)

Shared instruction for the **two active agents** (by default **Claude** and
**Codex**) to cooperate through a single
`M8SHIFT.md` file, in strict alternation (mutex), with periodic polling. Portable:
this protocol is identical in every project; only the title of `M8SHIFT.md`
changes.

Read it **once at the start of a session** as soon as you see a `M8SHIFT.md` at
the root of a project. You are **one of the two active agents** declared in the
`agents:` field of `M8SHIFT.md` (by default `claude` and `codex`) — identify yourself
by your anchor file.

---

## 0. TL;DR — the self-contained loop

You have just arrived in the project and you see a `M8SHIFT.md`: here is the
complete, copy-pasteable loop, **no other instruction is required**. `<you>` is your
own agent name and `<other>` is the other active agent (the pair declared in
`agents:`; by default `claude` / `codex`, via the `CLAUDE.md` / `AGENTS.md` anchors).

```bash
# 1. Am I expected? (NON-blocking commands)
./m8shift.py status                 # read the `state` field
./m8shift.py wait <you> --once      # rc 0 = you may acquire ; rc 3 = not yet

# 2. ACQUIRE the pen BEFORE working (EXCLUSIVE acquisition: when two agents
#    try at the same time, only one succeeds):
./m8shift.py claim <you>           # rc 0 = you hold the pen ; rc != 0 = not your turn
#    • If claim SUCCEEDS: read the `ask:` that <other> left you in the last
#      turn (at IDLE startup / turn 0, nothing to honour), do the work in the
#      repository, THEN record your turn and hand off:
./m8shift.py append <you> --to <other> \
    --ask "what you expect from the other" \
    --done "what you just did" \
    --files file1,file2
#    • If claim FAILS: it is not (or no longer) your turn → go back to waiting.

# 3. Not your turn: touch NOTHING. Block until your turn, then resume at 2:
./m8shift.py wait <you>             # poll every ~60 s (--interval N)
```

Golden rule: **you work and write only if you have acquired the pen via
`claim`.** `claim` is exclusive; `append` is accepted only if you hold the
pen. Everything else in this document is just the detail of this loop.

> The protocol makes you self-sufficient *once you are running*. In an interactive UI
> (VS Code, …) a human still resumes you between turns — `wait` blocks a process, it
> does not wake your chat UI. Fully hands-off relays need a headless runner, not a
> change to this protocol.

---

## 1. Mental model

- **A single living file**: `M8SHIFT.md`. The entire work dialogue is there.
- **A single pen, explicitly acquired**: to work, you **take** the pen via
  `claim` → state `WORKING_<you>`. `claim` is **exclusive** (two agents trying
  at the same time: only one succeeds). You modify the repository **only** while
  you hold the pen.
- **`append` closes your turn**: it is accepted only from `WORKING_<you>`,
  writes the turn and hands off (`AWAITING_<other>`). No `claim` ⇒ no `append`.
- **Strict alternation**: the two active agents take turns (e.g. `claude` → `codex`
  → `claude` …). Each hand-off is a numbered *turn* (`TURN`), framed by `BEGIN`/`END`.
- **Poll**: when it is not your turn, you wait (`./m8shift.py wait <you>`,
  ~60 s) then you retry `claim`.

---

## 2. The LOCK block (the mutex)

Delimited by `<!-- M8SHIFT:LOCK:BEGIN -->` … `<!-- M8SHIFT:LOCK:END -->`.
Fields (one `key: value` per line, easy to `grep`):

| field     | values | meaning |
|-----------|---------|------|
| `holder`  | an active agent \| `none` | who holds the pen (default `claude`/`codex`) |
| `state`   | `IDLE` \| `WORKING_<X>` \| `AWAITING_<X>` \| `DONE` | current state (`<X>` = an active agent, uppercased) |
| `agents`  | CSV, e.g. `claude,codex` | the relaying pair (the first two declared); default `claude,codex` |
| `turn`    | integer | number of the last closed turn |
| `since`   | ISO-8601 UTC | since when this state has lasted |
| `expires` | ISO-8601 UTC \| `-` | anti-deadlock takeover deadline (TTL 30 min) |
| `note`    | short text | readable memo |

> `expires` carries a date **only** during `WORKING_*` (an agent is working,
> TTL 30 min). It returns to `-` as soon as we are waiting (`AWAITING_*`, `IDLE`,
> `DONE`): nobody holds the pen, so there is no staleness to watch.

**Reading the states** (`<X>` is an active agent — by default `claude`/`codex`):
- `AWAITING_<X>` → it is `<X>`'s turn to play (the other agent waits).
- `WORKING_<X>` → `<X>` holds the pen and is working (the other waits, touches nothing).
- `IDLE` → nobody has the hand, the first who has something to say starts.
- `DONE` → session closed, no further relay expected.

---

## 3. Format of a turn

```
<!-- M8SHIFT:TURN <n> <agent> BEGIN -->
- from:    <agent>           # an active agent
- to:      <agent|none>      # to whom you hand off
- ask:     <what you expect from the other, precise and actionable>
- done:    <what you just did>
- files:   <files touched, comma-separated>
- handoff: <agent|none>      # = to ; deliberate redundancy, grep-friendly
<blank line>
<free body: explanations, questions, code blocks, lists>
<!-- M8SHIFT:TURN <n> <agent> END -->
```

Rules:
- A **closed** turn (`END` set) is **immutable**. To react, you open the next
  turn. Never retroactive rewriting.
- `ask` must be actionable: the other agent must be able to start without asking
  you again. If you expect nothing (just an FYI), put `ask: —`.
- Keep a turn **bounded**: if it exceeds ~150 lines or several topics, split it
  into several successive turns (one topic = one turn).

---

## 4. Work cycle (each agent's loop)

```
loop:
  1. read LOCK (status / wait)
  2. if state == AWAITING_<me> or IDLE:
       a. CLAIM  : ./m8shift.py claim <me>   → state=WORKING_<ME>, expires=now+30min
                   EXCLUSIVE: if someone else has taken the pen in the meantime,
                   claim FAILS → go to 3.
       b. WORK in the repository (while you hold the pen, you alone)
       c. APPEND  : ./m8shift.py append <me> --to <other>
                   writes my turn <turn+1>, state=AWAITING_<OTHER>
  3. else (WORKING_<other> or AWAITING_<other>):
       wait ~60 s (wait), go back to 1
  4. if state == DONE: exit
```

In practice: `claim` **acquires** the pen (exclusive), `append` **closes** your
turn and hands off, `wait` waits for your turn. The explicit acquisition before
working is what guarantees that a single agent modifies the repository at a time.

> **Concurrency model (two levels)**:
> 1. **Transitions** serialized by an inter-process lock (`.m8shift.lock`,
>    `O_CREAT|O_EXCL`, with an ownership token): each read-modify-write of the
>    LOCK + atomic write (unique temporary + `os.replace`) is exclusive.
> 2. **Work window** protected by the persistent state `WORKING_<agent>`:
>    `claim` is the only acquisition, and it fails if someone else holds or has
>    already taken the pen. Two simultaneous `claim`s from `IDLE` ⇒ **only one
>    succeeds**; the other must wait. Since we work only after a successful
>    `claim`, two agents never modify the repository at the same time.
>
> An abandoned `.m8shift.lock` (killed process) is taken over after 60 s, token
> verified. *Limits*: the lock is **advisory** (a manual edit of `M8SHIFT.md`
> bypasses it); on a network FS (NFS) `O_EXCL`/`rename` are less reliable —
> cowork targets a repository on local disk. See also §0/§4 (mandatory claim).

---

## 5. Anti-deadlock (stale lock)

If the other agent crashes while holding the pen, the lock would stay stuck.
Guardrail:
- on CLAIM, we set `expires = now + 30 min`;
- if you see `state == WORKING_<other>` **and** `now > expires`, the lock is
  **stale**: take it over with `./m8shift.py claim <you> --force`, then open a
  turn noting the takeover (`done: takeover after stale lock from <other>`);
- **the tool enforces the rule**: `--force` is **refused** on a still-valid
  lock. You therefore cannot steal the pen from an active agent (this is
  intentional);
- you can **refresh your own** lock before it expires: `./m8shift.py claim
  <you>` when you already hold it resets `expires` to +30 min;
- `release` and `done` act only if **you** hold the pen (or if nobody holds it);
  `--force` overrides, reserved for recovery.

---

## 6. Keeping it bounded over time (bounded length)

`M8SHIFT.md` must not grow indefinitely:
- keep in `M8SHIFT.md` the `LOCK` block + the **~6 last turns**;
- `./m8shift.py archive --keep 6` moves the older turns (already closed) to
  `M8SHIFT.archive.md` (append), without ever touching the lock or the last open
  turn.
- The archive can be consulted but is **never** re-read by the loop: only the
  living part of `M8SHIFT.md` drives the relay.

---

## 7. The `m8shift.py` tool

```
./m8shift.py init [--name PROJECT] [--agents a,b] [--lang en|fr] [--force]  # (re)generates the kit here
./m8shift.py status                                # lock + last turn (NON-blocking)
./m8shift.py wait <agent> [--once] [--interval N]  # waits for your turn ; --once = 1 check (rc 3 if not your turn)
./m8shift.py claim <agent> [--force]               # ACQUIRE the pen (exclusive) — from your turn /
                                                  #   IDLE / your own lock ; --force = stale lock ONLY
./m8shift.py append <agent> --to <other> \
     --ask "..." --done "..." [--files a,b] [--body file.md|-]   # closes your turn + hands off
./m8shift.py release <agent> --to <other> [--force]  # hand off without a body (does NOT re-increment turn)
./m8shift.py done <agent> [--force]                 # close the session (state=DONE)
./m8shift.py archive [--keep N]                     # purge old closed turns (never turn #0)
```

- **`claim` first**: you must hold the pen (`WORKING_<you>`) to `append`.
  `claim` is **exclusive** (a single winner if two agents try together).
- `append` is accepted **only from `WORKING_<you>`**; it writes the turn and
  hands off. `--body -` reads the body from stdin; `--body f.md` from a file;
  without `--body`, the turn has only the header.
- `--to` must target **the other** agent (self-hand-off refused: strict alternation).
- **Non-blocking** inspection: `status` or `wait <you> --once`. `wait <you>`
  **without** `--once` blocks until your turn — do not use it if you must return
  control to your loop in the meantime.

---

## 8. Adoption by any project (portability)

`m8shift.py` is **self-sufficient**: it embeds this protocol, the `M8SHIFT.md`
template and the anchors. To adopt the relay in a project:

```bash
cp /path/to/m8shift.py .          # copy the only file needed
./m8shift.py init                 # project name = folder name (otherwise --name)
```

`init`:
- writes `M8SHIFT.protocol.md` (this document) and `M8SHIFT.md` (a fresh IDLE
  lock); `M8SHIFT.md` is **not** overwritten if it already exists (except with
  `--force`) → the state of the ongoing relay is preserved;
- injects at the **top** a "Co-work relay" block into **each active agent's anchor**
  (by default `CLAUDE.md` and `AGENTS.md`; created if missing), between
  `M8SHIFT:STANZA` markers → **idempotent** re-injection (moves/updates the block
  without duplicating, existing content preserved; the prior file is backed up to
  `<anchor>.cowork.bak`);
- if `CLAUDE.md` existed but no Codex instruction (`AGENTS.md` or
  `AGENTS.override.md`) existed, automatically creates in `AGENTS.md` a bridge
  asking Codex to read the shared instructions in `CLAUDE.md`. A pre-existing
  Codex anchor is never completed or replaced automatically;
- renames a single `claude.md`/`agents.md` variant to the canonical
  auto-loaded name, including on a case-insensitive FS. Several coexisting
  variants are refused rather than silently merged. If Git is available and the
  variant is tracked, it uses `git mv -f` to also update the index;
- if `AGENTS.override.md` exists, it also synchronizes the stanza there: Codex
  loads this override instead of `AGENTS.md` in the same folder.

### Bootstrap / uptake by the agents

cowork is **passive**: it never "calls" any AI. It relies on the convention of each
host tool — **Claude reads `CLAUDE.md`, Codex reads `AGENTS.md`**, and any other active
agent reads its own anchor — at session/execution startup. The bootstrap chain is
therefore:

```mermaid
flowchart LR
    I["m8shift.py init"] --> S["inject the stanza into<br/>each active agent's anchor"]
    S --> R["each agent reads its anchor<br/>at session start"]
    R --> L["applies M8SHIFT.protocol.md<br/>(the wait / claim / work / append loop)"]
```

- **After `init`**: start a new session/execution of the agent. A session
  already open has generally built its instruction chain before the injection.
- **Interactive Codex or `codex exec`**: `AGENTS.md` is loaded if the command
  starts from the project root or one of its subfolders. *Headless* mode is not
  in itself a limit; a cron/CI launched outside the project, however, does not
  discover the anchor.
- **Codex override**: `AGENTS.override.md` masks `AGENTS.md` in the same folder;
  `init` therefore injects the stanza into both when it is present.
- **Codex size**: Codex stacks the instruction files up to a *combined* ceiling
  (`project_doc_max_bytes`, 32 KiB by default) and truncates the file that
  overflows to the remaining byte count. Putting the stanza at the top thus
  keeps it in priority (and a file closer to the cwd takes precedence);
  nevertheless keep the anchors **lightweight**.
- **General limit**: cowork cannot force an AI to read anything. Without a
  project root/context, point the agent explicitly to `M8SHIFT.protocol.md`.

Codex reference: https://developers.openai.com/codex/guides/agents-md
"""

STANZA_EN = """{begin}
## Co-work relay — self-contained (no human explanation needed)

You are **{me}** in this project. As soon as a `M8SHIFT.md` is present at the root,
it is your source of coordination with **{other}**: apply `M8SHIFT.protocol.md`
(read it once, see its §0) BEFORE any other work. **You only work and write if
you have acquired the pen via `claim`.**

```bash
./m8shift.py status                # who holds the pen? (non-blocking)
./m8shift.py wait {me} --once      # rc 0 = you may acquire ; rc 3 = not yet
```

- **Acquire first** (`state == AWAITING_{ME}` or `IDLE`):
  `./m8shift.py claim {me}` — **exclusive**: if {other} has already taken the pen, it
  fails → go back to waiting. If it succeeds, you hold the pen (`WORKING_{ME}`).
- **Then work and close your turn**: read the `ask:` that {other} left you
  (at IDLE startup, nothing to honor), do the work, then:
  `./m8shift.py append {me} --to {other} --ask "…" --done "…" [--files a,b]`
- **Not your turn**: touch nothing; `./m8shift.py wait {me}` blocks until your
  turn (poll ~60 s), then retry `claim`.
- **{other}'s lock is stale** (`WORKING_{OTHER}` + `now > expires`):
  `./m8shift.py claim {me} --force`.

A closed turn is immutable: to react, open the next turn.

_Interactive-UI note_: in a chat UI (VS Code, …) a human resumes you between turns —
`wait` blocks a process, it does not wake your UI. Fully hands-off relays need a
headless runner.
{end}"""

COWORK_EN = r"""<!-- ╔════════════════════════════════════════════════════════════╗
     ║  M8Shift · single-file multi-agent relay · protocol v1     ║
     ║  Read M8SHIFT.protocol.md BEFORE writing here.             ║
     ╚════════════════════════════════════════════════════════════╝ -->

# M8Shift · __PROJECT__

> Shared work file. **Only one agent writes at a time.** The lock is the
> `LOCK` block below. Only write if `state == AWAITING_<you>`. Details →
> [M8SHIFT.protocol.md](M8SHIFT.protocol.md). Tool → `./m8shift.py status`.

<!-- M8SHIFT:LOCK:BEGIN -->
holder:   none
state:    IDLE
agents:   __AGENTS__
lang:     __LANG__
turn:     0
since:    __NOW__
expires:  -
note:     session initialized, no turn opened
<!-- M8SHIFT:LOCK:END -->

---

## Turn log

<!-- Turns stack below, from oldest to most recent.                          -->
<!-- Turn format: see M8SHIFT.protocol.md §3. Never edit a turn that is        -->
<!-- already closed (END set): add a new turn instead.                        -->

<!-- M8SHIFT:TURN 0 system BEGIN -->
- from:    system
- to:      none
- ask:     —
- done:    Relay initialization. The first agent that starts runs
           `./m8shift.py claim __A__` (or `__B__`), works, then
           `./m8shift.py append __A__ --to __B__ --ask "..." --done "..."`.
- files:   M8SHIFT.md, M8SHIFT.protocol.md, m8shift.py
- handoff: none
<!-- M8SHIFT:TURN 0 system END -->
"""

BRIDGE_EN = """## Shared project instructions

Read and fully apply `CLAUDE.md`, which contains the shared project instructions
for Claude and Codex.
"""

PROTOCOL = {"en": PROTOCOL_EN}
STANZA = {"en": STANZA_EN}
COWORK_TPL = {"en": COWORK_EN}
BRIDGE = {"en": BRIDGE_EN}
LANGS = tuple(PROTOCOL)   # languages built into THIS file (en + any injected)

# ----------------------------------------------------------------- i18n (en/fr)
# Resolved language: --lang (init) > $M8SHIFT_LANG > LOCK `lang` field > en.

def resolve_lang(explicit=None, lk=None):
    if explicit in LANGS:
        return explicit
    env = os.environ.get("M8SHIFT_LANG", "")
    if env in LANGS:
        return env
    if lk and lk.get("lang") in LANGS:
        return lk["lang"]
    return DEFAULT_LANG

LANG = resolve_lang()  # baseline (refined by load_or_die / cmd_init)

MESSAGES = {
    "en": {
        "lock_busy": "internal lock busy (another m8shift.py is writing) — retry.",
        "cowork_missing": "M8SHIFT.md not found — run `./m8shift.py init` first.",
        "lock_missing": "{file} corrupted: LOCK block not found — `./m8shift.py init --force` to reset the lock.",
        "lock_invalid": "{file} corrupted (invalid LOCK: {errs}) — `./m8shift.py init --force` to repair.",
        "field_newline": "refused: {label} must not contain a line break.",
        "field_reserved": "refused: {label} contains a reserved marker ({marker}).",
        "bad_agent": "invalid agent: {a} (expected: {agents})",
        "bad_roster": "invalid --agents: {raw} — provide at least two distinct agent names (e.g. claude,codex).",
        "anchor_no_map": "{agent}: no known anchor file — bootstrap manually (point {agent} to M8SHIFT.protocol.md).",
        "anchor_collision": "{agent}: anchor {filename} is already used by another active agent — skipped (bootstrap {agent} manually).",
        "roster_extra": "{n} agents active in the relay: {agents}.",
        "roster_conflict": "refused: --agents {requested} differs from the roster {existing} already declared — re-run with --force to reset it, or omit --agents to keep the current roster.",
        "anchor_ambiguous": "ambiguous anchors for {canonical}: {others} — consolidate them before `m8shift.py init`.",
        "anchor_git_fail": "could not rename {actual} via Git to {canonical}: {detail}",
        "git_unknown_err": "unknown git error",
        "migrated_git": "{actual} → {canonical}: renamed via Git for auto-loading",
        "migrated_fs": "{actual} → {canonical}: renamed for auto-loading",
        "stanza_incomplete": "{filename}: incomplete M8Shift stanza — fix the markers before init.",
        "stanza_updated": "stanza refreshed at top",
        "stanza_added": "stanza added at top",
        "file_created": "file created",
        "anchor_result": "{filename}: {action}",
        "proto_written": "{file}: written",
        "proto_uptodate": "{file}: already up to date",
        "cowork_preserved": "{file}: preserved (already exists; --force to reset)",
        "cowork_written": "{file}: written (project “{name}”, lock IDLE)",
        "bridge_added": "AGENTS.md: automatic bridge to the shared instructions in CLAUDE.md",
        "override_synced": "{filename}: Codex override active, stanza synced",
        "init_header": "✓ m8shift init — project “{name}” in {here}",
        "init_start": "Start: ./m8shift.py claim {a}  (then work, then ./m8shift.py append {a} --to {b} --ask \"…\" --done \"…\")",
        "init_bootstrap": "Bootstrap: start a new session/run of each agent to reload its anchor.",
        "status_stale": "  ⚠ stale lock — reclaim with: claim <you> --force",
        "last_turn": "── last turn: #{n} by {who}",
        "wait_your_turn": "✓ your turn ({st}) — `./m8shift.py claim {agent}` to acquire the pen.",
        "wait_free": "✓ free ({st}) — `./m8shift.py claim {agent}` to acquire the pen.",
        "wait_done": "session DONE — nothing to wait for.",
        "wait_stale": "⚠ {other}'s lock is stale — claim --force possible.",
        "wait_not_yet": "… not your turn: {st} (holder={holder}).",
        "wait_poll": "… {st} (holder={holder}), re-checking in {interval}s",
        "bad_interval": "--interval must be an integer >= 1.",
        "claim_active": "refused: {holder}'s lock is still valid (expires {expires}). --force only reclaims a stale lock (protocol §5).",
        "claim_refused": "refused: state={st}, holder={holder} — it is not your turn.",
        "note_reclaim": "reclaimed after {holder}'s stale lock",
        "note_holds": "{agent} holds the pen",
        "claim_ok": "✓ pen taken by {agent} (expires {expires}{suffix}).",
        "claim_reclaim_suffix": " — stale lock reclaimed",
        "body_error": "--body: {e}",
        "to_self_append": "refused: --to must target the other agent (strict alternation, protocol §1).",
        "append_need_claim": "refused: you do not hold the pen (state={st}) — run `./m8shift.py claim {agent}` first (exclusive acquisition), then append.",
        "note_turn": "turn {n} posted by {agent}, awaiting {to}",
        "append_ok": "✓ turn {n} written by {agent}, handed off to {to}.",
        "to_self": "refused: --to must target the other agent.",
        "not_holder_release": "refused: {holder} holds the pen, not you (--force to override).",
        "note_release": "handed off to {to} by {agent} (no turn)",
        "release_ok": "✓ handed off to {to}.",
        "not_holder_done": "refused: {holder} holds the pen, not you (--force to close anyway).",
        "note_done": "session closed by {agent}",
        "done_ok": "✓ session DONE.",
        "archive_none": "nothing to archive ({n} archivable turn(s), keep={keep}).",
        "archive_header": "# M8Shift · turn archive\n\n",
        "archive_ok": "✓ {n} turn(s) archived → {file} (kept: {keep}).",
        "recap_turns": "── last {n} turn(s) ──────────────────────",
        "peek_none": "(no handoff addressed to {agent} yet)",
        "field_no_eq": "--field expects KEY=VALUE, got {item!r}.",
        "field_bad_key": "rejected: advisory field key {key!r} is not snake_case / x_* ([a-z][a-z0-9_]*).",
        "field_reserved_key": "rejected: {key!r} is an engine-managed turn field — it is set automatically.",
        "field_dup_key": "rejected: advisory field {key!r} given more than once.",
        "memory_header": "# M8Shift · shared memory\n\n",
        "recap_memory": "── last {n} note(s) ────────────────────",
        "remember_ok": "✓ noted by {agent} → {file} ({n} note(s)).",
        "memory_empty": "refused: --note is empty after trimming — nothing to remember.",
        "check_overlap": "⚠ overlap (exact token match): {file} touched in #{n} by {who}",
        "check_no_overlap": "✓ no overlap: none of your {k} file(s) appear in the window{since}.",
        "check_hot": "🔥 hot files in window{since}: {list}",
        "check_window_empty": "(no files recorded in window{since})",
        "check_window_since": " since your last turn (#{n})",
        "check_window_lastn": " (last {n} turn(s))",
        "check_flags_need_check": "--files / --turns are read-only probe options — use them with --check.",
        "check_advisory_footer": "(advisory only — does not block claim; exact token match, "
                                 "normalize --files to the journal's spelling)",
        "tasks_header": "# M8Shift · tasks\n\n",
        "task_empty": "refused: the task description is empty after trimming.",
        "task_add_ok": "✓ #{id} added by {agent} → {file} ({n} open).",
        "task_event_ok": "✓ #{id} {verb} by {agent} → {file}.",
        "task_unknown": "refused: no open task #{id}.",
        "task_none": "(no open tasks)",
        "recap_tasks": "── {n} open task(s) ─────────────────────",
    },
}

def tr(msg, **kw):
    # NB: first param is `msg`, NOT `key` — several messages take a `key=` kwarg (e.g.
    # field_bad_key), which would collide with a positional named `key`.
    cat = MESSAGES.get(LANG, MESSAGES[DEFAULT_LANG])
    s = cat.get(msg) or MESSAGES[DEFAULT_LANG].get(msg, msg)
    return s.format(**kw) if kw else s

def now():
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0)

def iso(t):
    return t.strftime("%Y-%m-%dT%H:%M:%SZ")

def parse_iso(s):
    s = (s or "").strip()
    if not s or s == "-":
        return None
    try:
        return dt.datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=dt.timezone.utc)
    except ValueError:
        return None

def read(path=COWORK):
    with open(path, encoding="utf-8") as f:
        return f.read()

def _current_umask():
    m = os.umask(0)
    os.umask(m)
    return m

def write(text, path=COWORK):
    """Atomic write: UNIQUE temporary file + os.replace, preserving the mode of the
    existing target file (mkstemp forces 0600 otherwise)."""
    d = os.path.dirname(path) or "."
    os.makedirs(d, exist_ok=True)  # nested anchors (e.g. .github/…) need their parent
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".m8shift-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        try:
            os.chmod(tmp, os.stat(path).st_mode)  # keep the existing mode
        except OSError:
            os.chmod(tmp, 0o666 & ~_current_umask())  # new file: usual mode
        os.replace(tmp, path)  # atomic replacement
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise

@contextlib.contextmanager
def file_lock(timeout=LOCK_TIMEOUT):
    """Inter-process lock via exclusive file creation (O_CREAT|O_EXCL).

    Serializes the LOCK read-modify-write: two concurrent `m8shift.py` runs cannot
    mutate `M8SHIFT.md` at the same time. The lock carries an **ownership token**: we
    only remove it (at the end of the section, or when taking over a lock abandoned
    for LOCK_STALE_S) after verifying the token, so we never erase a successor's
    lock.
    """
    token = f"{os.getpid()}:{time.time_ns()}".encode()
    start = time.monotonic()
    while True:
        try:
            fd = os.open(LOCKFILE, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            try:
                os.write(fd, token)
            finally:
                os.close(fd)
            break
        except FileExistsError:
            try:
                victim_age = time.time() - os.path.getmtime(LOCKFILE)
                if victim_age > LOCK_STALE_S:
                    with open(LOCKFILE, "rb") as f:
                        victim = f.read()
                    # still stale AND unchanged since the read → safe takeover
                    if time.time() - os.path.getmtime(LOCKFILE) > LOCK_STALE_S:
                        with open(LOCKFILE, "rb") as f2:
                            if f2.read() == victim:
                                os.unlink(LOCKFILE)
                                continue
            except OSError:
                pass
            if time.monotonic() - start > timeout:
                sys.exit(tr("lock_busy"))
            time.sleep(0.05)
    try:
        yield
    finally:
        # remove ONLY our own lock (token verified)
        try:
            with open(LOCKFILE, "rb") as f:
                mine = f.read() == token
            if mine:
                os.unlink(LOCKFILE)
        except OSError:
            pass

def require_cowork():
    if not os.path.exists(COWORK):
        sys.exit(tr("cowork_missing"))

def load_or_die():
    """Read the living relay file while validating the LOCK block (presence AND
    schema); clean exit otherwise — no invalid value must reach the logic (no
    traceback). Validates the M8Shift LOCK markers."""
    require_cowork()
    text = read()
    begin, end = LOCK_BEGIN, LOCK_END
    if begin not in text or end not in text:
        sys.exit(tr("lock_missing", file=os.path.basename(COWORK)))
    lk = get_lock(text)
    globals()["LANG"] = resolve_lang(lk=lk)  # localize the validation errors below
    roster = active_agents(lk)               # ALL active agents (N), not just the first 2
    errs = []
    if "agents" in lk:
        ag_valid, ag_invalid = roster_tokens(lk["agents"])
        # `< 2` is the degree-1 FLOOR (>=2 agents, one writer), NOT a degree-2 cap —
        # the cap lived only in active_pair's [:2]. Do not "generalize" this away.
        if ag_invalid or len(ag_valid) < 2:  # reject a partially-invalid stored roster
            errs.append(f"agents={lk.get('agents')!r}")
    if lk.get("state") not in valid_states(roster):
        errs.append(f"state={lk.get('state')!r}")
    if not re.fullmatch(r"\d+", lk.get("turn", "")):
        errs.append(f"turn={lk.get('turn')!r}")
    if lk.get("holder") not in set(roster) | {"none"}:
        errs.append(f"holder={lk.get('holder')!r}")
    # validate against KNOWN_LANGS (a curated superset), NOT the build-local LANGS, so a file
    # whose lang isn't bundled here is still loadable (resolve_lang downgrades it to en).
    if lk.get("lang") not in (None, *KNOWN_LANGS):
        errs.append(f"lang={lk.get('lang')!r}")
    if errs:
        sys.exit(tr("lock_invalid", file=os.path.basename(COWORK), errs=", ".join(errs)))
    globals()["ROSTER"] = roster
    return text

def clean_field(label, val):
    """Single-line field: rejects line breaks and reserved markers (injection-safe).
    'Line break' = any char str.splitlines() splits on (parse_turns uses splitlines), so a
    value can never forge an extra `- key: value` line — not just LF/CR but VT/FF/FS/GS/RS/
    NEL/LS/PS too."""
    val = (val or "").strip()
    if any(c in val for c in LINE_BREAKS):
        sys.exit(tr("field_newline", label=label))
    for r in RESERVED:
        if r in val:
            sys.exit(tr("field_reserved", label=label, marker=r))
    return val

def clean_body(text):
    """Multi-line body: neutralizes any injected reserved marker (zero-width after the
    brand prefix), for BOTH brands, so it cannot masquerade as a real turn."""
    return text.replace("M8SHIFT:", "M8SHIFT\u200b:")

def get_lock(text):
    begin, end = LOCK_BEGIN, LOCK_END
    i = text.index(begin) + len(begin)
    j = text.index(end)
    fields = {}
    for line in text[i:j].splitlines():
        line = line.strip()
        m = re.match(r"([a-z_]+):\s*(.*)$", line)
        if m:
            fields[m.group(1)] = m.group(2).strip()
    return fields

def set_lock(text, fields):
    begin, end = LOCK_BEGIN, LOCK_END
    i = text.index(begin) + len(begin)
    j = text.index(end)
    body = "\n" + "\n".join(
        f"{k}:{' ' * max(1, 9 - len(k))}{v}"
        for k, v in fields.items()
    ) + "\n"
    return text[:i] + body + text[j:]

def roster_tokens(raw):
    """Split a roster CSV into (valid, invalid). Valid = normalized AGENT_RE names
    (lowercased, de-duplicated, order kept); invalid = non-empty tokens that are not
    a well-formed agent name. Empty tokens (trailing comma) are ignored, not invalid."""
    valid, invalid = [], []
    for tok in (raw or "").split(","):
        s = tok.strip()
        if not s:
            continue
        n = s.lower()
        if re.fullmatch(AGENT_RE, n):
            if n not in valid:
                valid.append(n)
        else:
            invalid.append(s)
    return valid, invalid

def parse_roster_csv(raw):
    """Valid agents from a CSV (lenient: empty/invalid tokens are ignored)."""
    return roster_tokens(raw)[0]

def roster_full(lk):
    """Full declared roster (>=2 names); falls back to the default pair if absent/invalid."""
    names = parse_roster_csv(lk.get("agents", ""))
    return names if len(names) >= 2 else list(AGENTS)

def active_pair(lk):
    """The first 2 declared agents — kept ONLY for the 2-name init/migrate template
    fill (__A__/__B__) and positional anchor indexing. NOT the N-agent source: use
    active_agents() for validation, roster and display."""
    return tuple(roster_full(lk)[:2])

def active_agents(lk):
    """The full ACTIVE roster (all declared agents, >=2) — the N-aware source for
    load_or_die validation, roster checks, and status/recap display."""
    return tuple(roster_full(lk))

def valid_states(pair):
    s = {"IDLE", "DONE"}
    for a in pair:
        s.add(f"WORKING_{a.upper()}")
        s.add(f"AWAITING_{a.upper()}")
    return s

def other(agent):
    for a in ROSTER:
        if a != agent:
            return a
    return agent

def need_agent(a):
    if a not in ROSTER:
        sys.exit(tr("bad_agent", a=repr(a), agents=" | ".join(ROSTER)))
    return a

# ---------------------------------------------------------------- init / anchors

def ensure_canonical_anchor(canonical, create=True):
    """Return an auto-loadable anchor, along with its migration action if any.

    A single variant (`agents.md`) is renamed to the canonical name (`AGENTS.md`).
    On a case-insensitive FS, a two-step rename also forces the case of the on-disk
    entry. Several coexisting variants are ambiguous: we refuse rather than merge or
    silently overwrite user content.
    """
    try:
        on_disk = os.listdir(HERE)
    except OSError:
        on_disk = []

    variants = [f for f in on_disk if f.casefold() == canonical.casefold()]
    if canonical in variants:
        if len(variants) > 1:
            others = ", ".join(repr(v) for v in variants if v != canonical)
            sys.exit(tr("anchor_ambiguous", canonical=repr(canonical), others=others))
        return canonical, ""
    if not variants:
        return (canonical, "") if create else (None, "")
    if len(variants) > 1:
        names = ", ".join(repr(v) for v in variants)
        sys.exit(tr("anchor_ambiguous", canonical=repr(canonical), others=names))

    actual = variants[0]
    actual_path = os.path.join(HERE, actual)
    canonical_path = os.path.join(HERE, canonical)

    # If the variant is tracked by Git, a plain rename on a case-insensitive FS does
    # not update the index (`git add -A` would then keep agents.md). `git mv -f`
    # makes the case change durable in future clones.
    try:
        tracked = subprocess.run(
            ["git", "-C", HERE, "ls-files", "--error-unmatch", "--", actual],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        ).returncode == 0
    except OSError:
        tracked = False
    if tracked:
        moved = subprocess.run(
            ["git", "-C", HERE, "mv", "-f", "--", actual, canonical],
            capture_output=True,
            text=True,
            check=False,
        )
        if moved.returncode != 0:
            detail = (moved.stderr or moved.stdout).strip()
            sys.exit(tr("anchor_git_fail", actual=repr(actual), canonical=repr(canonical),
                        detail=detail or tr("git_unknown_err")))
        return canonical, tr("migrated_git", actual=actual, canonical=canonical)

    try:
        same_file = os.path.exists(canonical_path) and os.path.samefile(actual_path, canonical_path)
    except OSError:
        same_file = False
    if same_file:
        # A rename that only changes case is unreliable across OSes/filesystems.
        # Freeing the name first via an intermediate forces the canonical entry.
        intermediate = os.path.join(
            HERE, f".m8shift-anchor-{os.getpid()}-{time.time_ns()}.tmp"
        )
        os.replace(actual_path, intermediate)
        try:
            os.replace(intermediate, canonical_path)
        except BaseException:
            with contextlib.suppress(OSError):
                os.replace(intermediate, actual_path)
            raise
    else:
        os.replace(actual_path, canonical_path)
    return canonical, tr("migrated_fs", actual=actual, canonical=canonical)

def stanza_for(me):
    # Peers from the ACTIVE roster, not other() (a 2-agent helper). For a pair the single
    # peer reproduces the exact pre-N substitution → the rendered stanza is byte-identical,
    # so inject_anchor's idempotent re-injection never rewrites existing pair-mode anchors.
    # For N>2 a generic placeholder fills the (single) {other}/{OTHER} template slots.
    peers = [a for a in ROSTER if a != me]
    o, OT = (peers[0], peers[0].upper()) if len(peers) == 1 else ("<agent>", "<AGENT>")
    return STANZA[LANG].format(
        begin=STANZA_BEGIN, end=STANZA_END,
        me=me, ME=me.upper(), other=o, OTHER=OT,
    )

def anchor_exists(canonical):
    """Whether a case variant of an anchor already exists on disk."""
    try:
        return any(
            filename.casefold() == canonical.casefold()
            for filename in os.listdir(HERE)
        )
    except OSError:
        return False

def inject_anchor(filename, me, initial_content=""):
    path = os.path.join(HERE, filename)
    block = stanza_for(me)
    if os.path.exists(path):
        cur = read(path)
        has_begin = STANZA_BEGIN in cur
        has_end = STANZA_END in cur
        if has_begin != has_end:
            sys.exit(tr("stanza_incomplete", filename=filename))
        if has_begin:
            # Remove any prior stanza, even one placed at the end of the file. The current
            # version is reinserted at the top to stay prioritized if the host tool
            # truncates a large instruction file.
            pat = re.compile(
                re.escape(STANZA_BEGIN) + r".*?" + re.escape(STANZA_END), re.DOTALL,
            )
            remainder = pat.sub("", cur).lstrip("\n")
            action = tr("stanza_updated")
        else:
            remainder = cur
            action = tr("stanza_added")
        new = block + "\n"
        if remainder:
            new += "\n" + remainder
        if new != cur:  # back up the pre-init content before modifying an existing anchor
            write(cur, path + ".m8shift.bak")
    else:
        # Deliberate choice (tested): the stanza is the FIRST thing in the file, even
        # a new one, to stay prioritized/untruncated — no H1 title above it.
        new = block + "\n"
        if initial_content:
            new += "\n" + initial_content.rstrip() + "\n"
        action = tr("file_created")
    write(new, path)
    return tr("anchor_result", filename=filename, action=action)

def cmd_init(args):
    globals()["LANG"] = resolve_lang(explicit=getattr(args, "lang", "") or None)
    name = args.name or os.path.basename(HERE) or "project"
    results = []

    # --- roster (RFC stage 1): validate the requested CSV up front (CLI level).
    # An explicit but malformed token is rejected, never silently dropped.
    req_valid, req_invalid = roster_tokens(getattr(args, "agents", "") or "")
    if getattr(args, "agents", "") and (req_invalid or len(req_valid) < 2):
        sys.exit(tr("bad_roster", raw=repr(args.agents)))

    with file_lock():
        # Determine the ACTIVE pair UNDER the lock, so two concurrent inits cannot
        # compute different rosters before serializing. Pair = the first 2 declared
        # names; extras are stored but inactive until the N-agent mode.
        cowork_exists = os.path.exists(COWORK)
        existing = None
        if cowork_exists:
            try:
                existing_lk = get_lock(read(COWORK))
            except (OSError, ValueError):
                existing_lk = None
            if existing_lk is not None:
                # A preserved M8SHIFT.md (no --force) must carry a VALID roster — don't
                # silently keep a corrupt one; point to --force to repair / re-seed.
                if not args.force and "agents" in existing_lk:
                    ev, einv = roster_tokens(existing_lk["agents"])
                    if einv or len(ev) < 2:
                        sys.exit(tr("lock_invalid", file=os.path.basename(COWORK), errs=f"agents={existing_lk['agents']!r}"))
                existing = roster_full(existing_lk)
        if req_valid and cowork_exists and not args.force:
            # M8SHIFT.md is preserved (no --force): --agents must match the in-place
            # roster, else demand --force rather than silently ignoring it.
            if existing is not None and req_valid != existing:
                sys.exit(tr("roster_conflict", requested=",".join(req_valid),
                            existing=",".join(existing)))
            full = existing or req_valid
        elif req_valid and ((not cowork_exists) or args.force):
            full = req_valid
        elif cowork_exists and existing is not None:
            full = existing
        else:
            full = list(AGENTS)
        pair = tuple(full[:2])      # kept ONLY for the 2-name template fill (__A__/__B__)
        extra = full[2:]
        globals()["ROSTER"] = tuple(full)   # ACTIVE roster = ALL declared agents (N)

        # Capture the state BEFORE creating the anchors. The CLAUDE → Codex bridge
        # must only be offered when a project genuinely had Claude instructions but
        # no Codex instructions.
        had_claude_anchor = anchor_exists(CLAUDE_ANCHOR)
        had_codex_anchor = (
            anchor_exists(CODEX_ANCHOR) or anchor_exists(CODEX_OVERRIDE)
        )

        # protocol: canonical source, (re)written only if missing or different
        if not os.path.exists(PROTO) or read(PROTO) != PROTOCOL[LANG]:
            write(PROTOCOL[LANG], PROTO)
            results.append(tr("proto_written", file=os.path.basename(PROTO)))
        else:
            results.append(tr("proto_uptodate", file=os.path.basename(PROTO)))

        # M8SHIFT.md: preserved if it exists (state of the ongoing relay), unless --force
        if os.path.exists(COWORK) and not args.force:
            results.append(tr("cowork_preserved", file=os.path.basename(COWORK)))
        else:
            text = (COWORK_TPL[LANG].replace("__PROJECT__", name)
                    .replace("__NOW__", iso(now())).replace("__LANG__", LANG)
                    .replace("__AGENTS__", ",".join(full))
                    .replace("__A__", pair[0]).replace("__B__", pair[1]))
            write(text, COWORK)
            results.append(tr("cowork_written", file=os.path.basename(COWORK), name=name))

        # Anchors: the stanza is injected for EACH active agent (the FULL roster, N).
        # claude / codex keep their dedicated handling (CLAUDE → Codex bridge,
        # AGENTS.override.md sync). Any other roster agent gets a best-effort anchor
        # via the ANCHORS table (warning if it is unmapped or if its anchor file is
        # already taken by another active agent).
        injected = set()
        for ag in full:
            if ag == "claude":
                claude_anchor, migration = ensure_canonical_anchor(CLAUDE_ANCHOR)
                if claude_anchor in injected:
                    results.append(tr("anchor_collision", agent=ag, filename=claude_anchor))
                    continue
                if migration:
                    results.append(migration)
                results.append(inject_anchor(claude_anchor, "claude"))
                injected.add(claude_anchor)
            elif ag == "codex":
                codex_anchor, migration = ensure_canonical_anchor(CODEX_ANCHOR)
                if codex_anchor in injected:
                    results.append(tr("anchor_collision", agent=ag, filename=codex_anchor))
                    continue
                if migration:
                    results.append(migration)
                # AGENTS.override.md masks AGENTS.md in Codex: if it exists, we inject
                # into both so the stanza survives its later removal.
                codex_initial_content = (
                    BRIDGE[LANG]
                    if had_claude_anchor and not had_codex_anchor and "claude" in full
                    else ""
                )
                results.append(inject_anchor(
                    codex_anchor, "codex", initial_content=codex_initial_content
                ))
                injected.add(codex_anchor)
                if codex_initial_content:
                    results.append(tr("bridge_added"))

                codex_override, migration = ensure_canonical_anchor(CODEX_OVERRIDE, create=False)
                if migration:
                    results.append(migration)
                if codex_override:
                    results.append(inject_anchor(codex_override, "codex"))
                    results.append(tr("override_synced", filename=codex_override))
            else:
                anchor = ANCHORS.get(ag)
                if not anchor:
                    results.append(tr("anchor_no_map", agent=ag))
                    continue
                resolved, migration = ensure_canonical_anchor(anchor)
                if resolved in injected:
                    results.append(tr("anchor_collision", agent=ag, filename=resolved))
                    continue
                if migration:
                    results.append(migration)
                results.append(inject_anchor(resolved, ag))
                injected.add(resolved)

        if extra:  # N>2: announce the full active roster (all relay, not "first two")
            results.append(tr("roster_extra", n=len(full), agents=",".join(full)))

    print(tr("init_header", name=name, here=HERE))
    for r in results:
        print(f"  • {r}")
    print(tr("init_start", a=pair[0], b=pair[1]))
    print(tr("init_bootstrap"))
    return 0

# ---------------------------------------------------------------- relay commands

TURN_RE = re.compile(
    r"<!-- M8SHIFT:TURN (\d+) ([a-z][a-z0-9_-]*) BEGIN -->\n?"
    r"(.*?)"
    r"<!-- M8SHIFT:TURN \1 \2 END -->",
    re.DOTALL,
)

def parse_turns(text):
    """Read-only shared parser for the turn journal → [{n, agent, fields, body}].
    Leading `- key: value` lines become `fields` (key grammar [a-z][a-z0-9_]*; UNKNOWN keys
    are kept verbatim, never silently dropped); everything after the first non-field line is
    the free-text `body`. Used by peek/recap/log; never feeds coordination logic."""
    out = []
    for m in TURN_RE.finditer(text):
        lines = m.group(3).splitlines()
        fields, i = {}, 0
        while i < len(lines):
            fm = re.match(r"- ([a-z][a-z0-9_]*):\s*(.*)$", lines[i])
            if not fm:
                break
            fields[fm.group(1)] = fm.group(2).rstrip()
            i += 1
        out.append({
            "n": int(m.group(1)), "agent": m.group(2),
            "fields": fields, "body": "\n".join(lines[i:]).strip(),
        })
    return out


MEMORY_RE = re.compile(r"^- (\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ) (" + AGENT_RE + r"): (.*)$")


def parse_memory(text):
    """Read-only parser for the shared-memory ledger → [{ts, agent, note}] in FILE ORDER.
    Mirrors parse_turns' tolerance: anchored per-line match, greedy note (an embedded ': '
    never re-splits), non-matching lines (header / blanks / hand-edits) silently skipped,
    never raises. `ts` is an opaque DISPLAY string — never parsed back into logic, never
    sorted/deduped on (the ledger is a dumb, file-ordered record). Never feeds routing."""
    out = []
    for line in text.splitlines():
        m = MEMORY_RE.match(line)
        if m:
            out.append({"ts": m.group(1), "agent": m.group(2), "note": m.group(3)})
    return out


TASKS_RE = re.compile(r"^- #(\d+) (\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ) ([a-z][a-z0-9_]*) ("
                      + AGENT_RE + r"): (.*)$")


def parse_tasks(text):
    """Read-only parser for the task event log → [{id, ts, verb, author, text}] in FILE ORDER.
    Mirrors parse_memory exactly: anchored per-line match, greedy text, malformed/hand-edited
    lines silently skipped, never raises. `ts`/`verb` are opaque DISPLAY tokens — never parsed
    back into logic, never sorted on. The ledger is a dumb, file-ordered record; it NEVER feeds
    the mutex / routing (claim/append/wait/load_or_die never call this)."""
    out = []
    for line in text.splitlines():
        m = TASKS_RE.match(line)
        if m:
            out.append({"id": int(m.group(1)), "ts": m.group(2), "verb": m.group(3),
                        "author": m.group(4), "text": m.group(5)})
    return out


def fold_tasks(events):
    """Current view of the task log by a single left-to-right pass: a task's IDENTITY (description,
    author) is its first (add) event; its STATUS (verb) is its LATEST event — last-event-wins on
    status, exactly memory's most-recent-wins. ZERO cross-task logic (no dependency resolution,
    ordering, cycle/priority). Consumed ONLY by task list/show + recap; NEVER called from
    claim/append/release/wait/load_or_die."""
    cur = {}
    for ev in events:
        if ev["id"] in cur:
            cur[ev["id"]] = {**cur[ev["id"]], "verb": ev["verb"], "ts": ev["ts"]}
        else:
            cur[ev["id"]] = dict(ev)
    return cur


def cmd_recap(args):
    """Read-only session-start briefing: current LOCK + the last N turn summaries."""
    text = load_or_die()
    lk = get_lock(text)
    print("── LOCK ───────────────────────────────")
    for k in ("holder", "state", "agents", "turn", "since", "expires", "note"):
        v = ",".join(active_agents(lk)) if k == "agents" else lk.get(k, "")
        print(f"  {k:<8} {v}")
    turns = parse_turns(text)
    recent = turns[-args.turns:] if args.turns > 0 else turns
    if recent:
        print(tr("recap_turns", n=len(recent)))
        for t in recent:
            f = t["fields"]
            print(f"  #{t['n']} {f.get('from', t['agent'])} -> {f.get('to', '-')}: {f.get('done', '-')}")
    # shared-memory headlines — only when the ledger exists (absent ⇒ output unchanged)
    if os.path.exists(MEMORY):
        notes = parse_memory(read(MEMORY))
        tail = notes[-args.memory:] if args.memory > 0 else notes
        if tail:
            print(tr("recap_memory", n=len(tail)))
            for nt in tail:   # chronological (file order), like the turn recap
                print(f"  {nt['ts']} {nt['agent']}: {nt['note']}")
    # open-task headlines — only when the ledger exists (absent ⇒ output unchanged)
    if os.path.exists(TASKS):
        opent = [ev for ev in fold_tasks(parse_tasks(read(TASKS))).values() if ev["verb"] == "add"]
        opent.sort(key=lambda e: e["id"])
        tail = opent[-args.tasks:] if args.tasks > 0 else opent
        if tail:
            print(tr("recap_tasks", n=len(tail)))
            for ev in tail:
                print(f"  #{ev['id']} {ev['author']}: {ev['text']}")
    return 0

def cmd_peek(args):
    """Print the last handoff addressed to <agent> as parse-free key=value (+ body).
    rc 0 if it is your turn / free / done, rc 3 otherwise (mirrors `wait --once`)."""
    text = load_or_die()
    agent = need_agent(args.agent)
    st = get_lock(text).get("state", "")
    mine = [t for t in parse_turns(text) if t["fields"].get("to") == agent]
    if mine:
        t = mine[-1]
        for k, v in t["fields"].items():
            print(f"{k}={v}")
        if t["body"]:
            print()
            print(t["body"])
    else:
        print(tr("peek_none", agent=agent))
    return 0 if st in (f"AWAITING_{agent.upper()}", "IDLE", "DONE") else 3

def cmd_log(args):
    """Read-only relay timeline: one line per turn (chronological)."""
    text = load_or_die()
    turns = parse_turns(text)
    if args.all and os.path.exists(ARCHIVE):
        turns = parse_turns(read(ARCHIVE)) + turns
    turns.sort(key=lambda t: t["n"])
    if args.limit > 0:
        turns = turns[-args.limit:]
    for t in turns:
        f = t["fields"]
        frm, to = f.get("from", t["agent"]), f.get("to", "-")
        if args.oneline:
            print(f"#{t['n']} {frm} -> {to}  {f.get('done', '-')}")
        else:
            files = f.get("files", "-")
            nf = 0 if files in ("-", "") else len([x for x in files.split(",") if x.strip()])
            print(f"#{t['n']:<3} {frm:>8} -> {to:<8} ({nf} files)  done: {f.get('done', '-')}")
    return 0

def cmd_status(args):
    text = load_or_die()
    lk = get_lock(text)
    exp = parse_iso(lk.get("expires"))
    stale = (
        lk.get("state", "").startswith("WORKING_")
        and exp is not None
        and now() > exp
    )
    turns = re.findall(r"M8SHIFT:TURN (\d+) ([a-z][a-z0-9_-]*) BEGIN", text)
    last = {"n": int(turns[-1][0]), "agent": turns[-1][1]} if turns else None
    if getattr(args, "json", False):
        out = dict(lk)                       # raw LOCK fields…
        out["agents_active"] = active_agents(lk)  # full active roster (N)
        out["stale"] = stale
        out["last_turn"] = last
        print(json.dumps(out, ensure_ascii=False, sort_keys=True))
        return 0
    print("── LOCK ───────────────────────────────")
    for k in ("holder", "state", "lang", "turn", "since", "expires", "note"):
        print(f"  {k:<8} {lk.get(k, '')}")
        if k == "state":
            print(f"  {'agents':<8} {','.join(active_agents(lk))}")
    if stale:
        print(tr("status_stale"))
    if last:
        print(tr("last_turn", n=last["n"], who=last["agent"]))
    return 0

def cmd_wait(args):
    if not args.once and args.interval < 1:
        sys.exit(tr("bad_interval"))
    while True:
        text = load_or_die()              # sets ROSTER/LANG from the current file
        agent = need_agent(args.agent)    # validated against the current roster
        lk = get_lock(text)
        st = lk.get("state", "")
        target = f"AWAITING_{agent.upper()}"
        if st in (target, "IDLE"):
            key = "wait_your_turn" if st == target else "wait_free"
            print(tr(key, st=st, agent=agent))
            return 0
        if st == "DONE":
            print(tr("wait_done"))
            return 0
        exp = parse_iso(lk.get("expires"))
        # ANY other active agent's lock can be stale (N agents), not just "the other" of
        # a pair. Self-exclusion keeps pair mode byte-identical (we never report our own
        # stale lock here) and names the REAL holder, not other()'s first-non-self guess.
        if (st.startswith("WORKING_") and st != f"WORKING_{agent.upper()}"
                and exp and now() > exp):
            print(tr("wait_stale", other=lk.get("holder")))
            return 0
        if args.once:  # single, non-blocking poll: rc=3 = not (yet) your turn
            print(tr("wait_not_yet", st=st, holder=lk.get("holder")))
            return 3
        print(tr("wait_poll", st=st, holder=lk.get("holder"), interval=args.interval))
        time.sleep(args.interval)

def _files_in_turn(t):
    """Journal-side file tokens of a turn: split the files: CSV, trim, drop empty + the —
    placeholder (so `files: —` and empty fields never match)."""
    return [tok for tok in (x.strip() for x in t["fields"].get("files", "").split(","))
            if tok and tok != "—"]


def _overlap_window(turns, agent, n):
    """Advisory scope for the overlap report (NEVER affects readiness): the last `n` turns if
    n>0, else the turns AFTER your last authored turn (what others touched since you worked);
    all parsed turns if you have never authored one. Pure list slice — no I/O, no mutation."""
    if n > 0:
        return turns[-n:]
    mine = [t["n"] for t in turns if t["fields"].get("from") == agent]
    if not mine:
        return turns
    last = max(mine)
    return [t for t in turns if t["n"] > last]


def _window_label(turns, agent, n):
    """The localized ' since your last turn (#k)' / ' (last N turns)' fragment for the report."""
    if n > 0:
        return tr("check_window_lastn", n=n)
    mine = [t["n"] for t in turns if t["fields"].get("from") == agent]
    return tr("check_window_since", n=max(mine)) if mine else ""


def cmd_claim_check(args):
    """READ-ONLY advisory pre-claim probe (`claim --check`). Takes NO pen and mutates NOTHING:
    no file_lock, no set_lock, no write — `--force` is a guaranteed no-op here. Prints (1) claim
    readiness (rc 0/3, identical to `wait --once`) and (2) which of your --files were recently
    touched by others (the files: field of turns in the window). Overlap is advisory text only —
    it NEVER changes the rc and NEVER feeds the mutex / routing."""
    text = load_or_die()                 # read-only; sets ROSTER/LANG, validates the LOCK
    agent = need_agent(args.agent)
    # validate --files UP-FRONT (rc 1 on injection) so a rejection never emits a readiness line;
    # dedup (order-preserving) so a repeated token can't amplify the overlap output.
    wanted = list(dict.fromkeys(
        tok for tok in (x.strip() for x in clean_field("--files", args.files).split(","))
        if tok and tok != "—"))
    lk = get_lock(text)
    st = lk.get("state", "")
    exp = parse_iso(lk.get("expires"))
    # readiness — mirrors cmd_wait --once exactly (parity asserted by test)
    if st in (f"AWAITING_{agent.upper()}", "IDLE"):
        print(tr("wait_your_turn" if st != "IDLE" else "wait_free", st=st, agent=agent))
        ready = True
    elif st == "DONE":
        print(tr("wait_done"))
        ready = True
    elif (st.startswith("WORKING_") and st != f"WORKING_{agent.upper()}"
          and exp and now() > exp):
        print(tr("wait_stale", other=lk.get("holder")))
        ready = True
    else:
        print(tr("wait_not_yet", st=st, holder=lk.get("holder")))
        ready = False
    # overlap report — pure parse_turns read, display only
    turns = parse_turns(text)
    window = _overlap_window(turns, agent, args.turns)
    since = _window_label(turns, agent, args.turns)
    touched = {}                          # file token -> (turn n, author), most-recent wins
    for t in window:
        for tok in _files_in_turn(t):
            touched[tok] = (t["n"], t["fields"].get("from", t["agent"]))
    if wanted:
        hits = [(w, *touched[w]) for w in wanted if w in touched]
        if hits:
            for f, n, who in hits:
                print(tr("check_overlap", file=f, n=n, who=who))
        else:
            print(tr("check_no_overlap", k=len(wanted), since=since))
    elif touched:
        lst = ", ".join(f"{f} (#{n} {who})" for f, (n, who) in touched.items())
        print(tr("check_hot", since=since, list=lst))
    else:
        print(tr("check_window_empty", since=since))
    print(tr("check_advisory_footer"))
    return 0 if ready else 3              # rc = readiness only; NO write/set_lock/file_lock above


def cmd_claim(args):
    if args.check:                       # read-only probe — never reaches the file_lock body below
        return cmd_claim_check(args)
    if args.files or args.turns:         # probe-only flags on a real claim = a likely typo, not a no-op
        sys.exit(tr("check_flags_need_check"))
    with file_lock():
        text = load_or_die()             # sets ROSTER/LANG from the on-disk file…
        agent = need_agent(args.agent)   # …so the agent is validated against it
        lk = get_lock(text)
        st = lk.get("state", "")
        holder = lk.get("holder", "none")
        exp = parse_iso(lk.get("expires"))
        stale = st.startswith("WORKING_") and exp is not None and now() > exp
        # your turn / IDLE / your own lock (TTL refresh); --force ONLY if stale.
        mine = st in ("IDLE", f"AWAITING_{agent.upper()}", f"WORKING_{agent.upper()}")
        if not (mine or (args.force and stale)):
            if args.force and st.startswith("WORKING_"):
                sys.exit(tr("claim_active", holder=holder, expires=lk.get("expires")))
            sys.exit(tr("claim_refused", st=st, holder=holder))
        reclaim = args.force and stale and holder not in (agent, "none")
        t = now()
        lk.update(
            holder=agent,
            state=f"WORKING_{agent.upper()}",
            since=iso(t),
            expires=iso(t + dt.timedelta(minutes=TTL_MIN)),
            note=(tr("note_reclaim", holder=holder) if reclaim
                  else tr("note_holds", agent=agent)),
        )
        write(set_lock(text, lk))
    suffix = tr("claim_reclaim_suffix") if reclaim else ""
    print(tr("claim_ok", agent=agent, expires=lk["expires"], suffix=suffix))
    return 0

def _read_body(spec):
    if not spec:
        return ""
    if spec == "-":
        return sys.stdin.read().rstrip("\n")
    try:
        with open(spec, encoding="utf-8") as f:
            return f.read().rstrip("\n")
    except OSError as e:
        sys.exit(tr("body_error", e=e))

def collect_advisory_fields(args):
    """§5 advisory turn fields: sugar flags (branch/commit/tests/next/blocked_on) + the open
    `--field key=value` namespace (x_* and any other key). Returns an ordered [(key, value)]:
    values are clean_field-checked, keys must be snake_case/x_* and may not shadow an
    engine-managed routing field, no key twice. Pure passthrough — never interpreted."""
    out, seen = [], set()

    def add(key, label, value):
        # validate the key BEFORE the empty-value short-circuit, so a bad/shadowing/dup key
        # is reported even when its value happens to be blank
        if not FIELD_KEY_RE.match(key):
            sys.exit(tr("field_bad_key", key=key))
        if key in ENGINE_FIELDS:
            sys.exit(tr("field_reserved_key", key=key))
        if key in seen:
            sys.exit(tr("field_dup_key", key=key))
        value = clean_field(label, value)
        if not value:
            return
        seen.add(key)
        out.append((key, value))

    for key, value in (("branch", args.branch), ("commit", args.commit),
                       ("tests", args.tests), ("next", args.next),
                       ("blocked_on", args.blocked_on)):
        add(key, "--" + key.replace("_", "-"), value)
    for item in args.field:
        key, sep, value = item.partition("=")
        if not sep:
            sys.exit(tr("field_no_eq", item=item))
        add(key.strip(), "--field", value)
    return out


def cmd_append(args):
    # Field/body reading stays OUTSIDE the critical section (stdin may block); agent
    # validation happens UNDER the lock, against the roster load_or_die reads.
    ask = clean_field("--ask", args.ask) or "—"
    done = clean_field("--done", args.done) or "—"
    files = clean_field("--files", args.files) or "—"
    body = clean_body(_read_body(args.body))
    advisory = collect_advisory_fields(args)  # §5: optional, passthrough, injection-safe

    with file_lock():
        text = load_or_die()
        agent = need_agent(args.agent)
        to = need_agent(args.to)
        if to == agent:
            sys.exit(tr("to_self_append"))
        lk = get_lock(text)
        st = lk.get("state", "")
        # append is allowed ONLY if you already hold the pen (prior exclusive claim).
        # This is what guarantees exclusivity of the WORK WINDOW, not just of the
        # journal write: you cannot work+append from IDLE.
        if st != f"WORKING_{agent.upper()}":
            sys.exit(tr("append_need_claim", st=st, agent=agent))
        n = int(lk.get("turn", "0")) + 1
        brand = "M8SHIFT"  # M8Shift-only: turn markers are always M8SHIFT:*
        block = (
            f"<!-- {brand}:TURN {n} {agent} BEGIN -->\n"
            f"- from:    {agent}\n"
            f"- to:      {to}\n"
            f"- ask:     {ask}\n"
            f"- done:    {done}\n"
            f"- files:   {files}\n"
            f"- handoff: {to}\n"
        )
        for key, value in advisory:   # §5: advisory fields follow the fixed routing block
            block += f"- {key}: {value}\n"
        if body:
            block += "\n" + body + "\n"
        block += f"<!-- {brand}:TURN {n} {agent} END -->\n"

        # insert the turn at the end of the file (append-only journal)
        text = text.rstrip("\n") + "\n\n" + block

        t = now()
        lk.update(
            holder=to,
            state=f"AWAITING_{to.upper()}",
            turn=str(n),
            since=iso(t),
            expires="-",
            note=tr("note_turn", n=n, agent=agent, to=to),
        )
        write(set_lock(text, lk))
    print(tr("append_ok", n=n, agent=agent, to=to))
    return 0

def cmd_release(args):
    with file_lock():
        text = load_or_die()
        agent = need_agent(args.agent)
        to = need_agent(args.to)
        if to == agent:
            sys.exit(tr("to_self"))
        lk = get_lock(text)
        holder = lk.get("holder", "none")
        if holder not in (agent, "none") and not args.force:
            sys.exit(tr("not_holder_release", holder=holder))
        t = now()
        lk.update(
            holder=to, state=f"AWAITING_{to.upper()}",
            since=iso(t), expires="-",
            note=tr("note_release", to=to, agent=agent),
        )
        write(set_lock(text, lk))
    print(tr("release_ok", to=to))
    return 0

def cmd_done(args):
    with file_lock():
        text = load_or_die()
        agent = need_agent(args.agent)
        lk = get_lock(text)
        holder = lk.get("holder", "none")
        if holder not in (agent, "none") and not args.force:
            sys.exit(tr("not_holder_done", holder=holder))
        t = now()
        lk.update(holder="none", state="DONE", since=iso(t), expires="-",
                  note=tr("note_done", agent=agent))
        write(set_lock(text, lk))
    print(tr("done_ok"))
    return 0

def cmd_remember(args):
    """Append one durable note to M8SHIFT.memory.md — passive, append-only, human-curated.
    Runs under file_lock (atomic write) but takes NO pen: note-taking is curation, not the
    exclusive work window, so any roster agent may remember from any state. HARD INVARIANT:
    this never calls set_lock and never mutates holder/state/turn/… — memory writes a
    DIFFERENT file and can never feed the mutex / routing."""
    note = clean_field("--note", args.note)   # single-line, injection-safe; outside the lock
    if not note:
        sys.exit(tr("memory_empty"))
    with file_lock():
        load_or_die()   # populate ROSTER/LANG + enforce the relay precondition (LOCK ignored)
        agent = need_agent(args.agent)
        line = "- " + iso(now()) + " " + agent + ": " + note + "\n"
        prev = read(MEMORY) if os.path.exists(MEMORY) else tr("memory_header")
        write(prev + line, MEMORY)   # atomic; lazy header on first note (cmd_archive pattern)
        n = len(parse_memory(prev + line))
    print(tr("remember_ok", agent=agent, file=os.path.basename(MEMORY), n=n))
    return 0


def _cmd_task_read(args):
    """Read-only task views (no lock): `list` (open by default; --all adds done/drop) and
    `show <id>` (one id's file-ordered event history)."""
    text = read(TASKS) if os.path.exists(TASKS) else ""
    if args.verb == "show":
        events = [e for e in parse_tasks(text) if e["id"] == args.id]
        if not events:
            sys.exit(tr("task_unknown", id=args.id))
        for e in events:
            print(f"  #{e['id']} {e['ts']} {e['verb']} {e['author']}: {e['text']}")
        return 0
    rows = sorted(fold_tasks(parse_tasks(text)).values(), key=lambda e: e["id"])
    if not args.all:
        rows = [e for e in rows if e["verb"] == "add"]   # open = last event is still 'add'
    if not rows:
        print(tr("task_none"))
        return 0
    for e in rows:
        mark = {"add": " ", "done": "x"}.get(e["verb"], "-")
        print(f"  [{mark}] #{e['id']} {e['author']}: {e['text']}")
    return 0


def cmd_task(args):
    """Append-only shared to-do ledger (M8SHIFT.tasks.md) — passive, pen-free, the dumb twin of
    `remember`. add/done/drop append ONE event line; list/show are read-only. Current status is a
    read-time last-event-wins fold (fold_tasks), NEVER a state machine. HARD INVARIANT: cmd_task
    never calls set_lock and never mutates the LOCK — task state can never feed the mutex /
    routing (claim/append/wait never read the task file). --for / blocked_on are advisory text,
    never enforced, never resolved into a dependency."""
    verb = args.verb
    if verb in ("list", "show"):
        return _cmd_task_read(args)
    desc = blocked = ""                   # clean user values OUTSIDE the lock (like cmd_remember)
    if verb == "add":
        desc = clean_field("desc", args.desc)
        if not desc:
            sys.exit(tr("task_empty"))
        if args.blocked_on:
            blocked = clean_field("--blocked-on", args.blocked_on)
    with file_lock():
        load_or_die()                     # ROSTER/LANG + relay precondition (LOCK ignored)
        author = need_agent(args.agent)
        prev = read(TASKS) if os.path.exists(TASKS) else tr("tasks_header")
        if verb == "add":
            forname = need_agent(args.for_) if args.for_ else ""   # advisory attribution only
            text = desc + (f" for:{forname}" if forname else "") + (f" blocked_on:{blocked}" if blocked else "")
            tid = 1 + max((ev["id"] for ev in parse_tasks(prev)), default=0)  # only derived value
            new = prev + f"- #{tid} {iso(now())} add {author}: {text}\n"
            write(new, TASKS)
            n = sum(1 for ev in fold_tasks(parse_tasks(new)).values() if ev["verb"] == "add")
        else:                             # done / drop <id>
            cur = fold_tasks(parse_tasks(prev)).get(args.id)
            if not cur or cur["verb"] != "add":   # unknown or already terminal — refuse a no-op
                sys.exit(tr("task_unknown", id=args.id))
            tid = args.id
            write(prev + f"- #{tid} {iso(now())} {verb} {author}: \n", TASKS)
    if verb == "add":
        print(tr("task_add_ok", id=tid, agent=author, file=os.path.basename(TASKS), n=n))
    else:
        print(tr("task_event_ok", id=tid, verb=verb, agent=author, file=os.path.basename(TASKS)))
    return 0


def cmd_archive(args):
    pat = re.compile(
        r"<!-- M8SHIFT:TURN (\d+) ([a-z][a-z0-9_-]*) BEGIN -->.*?<!-- M8SHIFT:TURN \1 \2 END -->\n?",
        re.DOTALL,
    )
    keep = max(0, args.keep)
    with file_lock():
        text = load_or_die()
        # the bootstrap turn #0 (system) always stays in the living file
        matches = [m for m in pat.finditer(text) if m.group(1) != "0"]
        if len(matches) <= keep:
            print(tr("archive_none", n=len(matches), keep=keep))
            return 0
        to_move = matches[:-keep] if keep else matches
        moved = "".join(m.group(0) for m in to_move)
        # remove from the living file (last to first to keep offsets valid)
        for m in reversed(to_move):
            text = text[:m.start()] + text[m.end():]
        text = re.sub(r"\n{3,}", "\n\n", text)
        prev = read(ARCHIVE) if os.path.exists(ARCHIVE) else tr("archive_header")
        write(prev + moved, ARCHIVE)  # atomic write (tmp + os.replace)
        write(text)
    print(tr("archive_ok", n=len(to_move), file=os.path.basename(ARCHIVE), keep=keep))
    return 0

def main():
    # prog follows the invoked name (m8shift.py).
    p = argparse.ArgumentParser(
        prog=os.path.basename(sys.argv[0]),
        description="Single-file multi-agent relay (M8Shift), portable.")
    sub = p.add_subparsers(dest="cmd", required=True)

    i = sub.add_parser("init", help="(re)generate the kit in this folder")
    i.add_argument("--name", default="")
    i.add_argument("--agents", default="",
                   help="comma-separated agent roster; the first two relay "
                        "(e.g. claude,codex). Extra names are reserved for the "
                        "future N-agent mode.")
    i.add_argument("--lang", choices=LANGS, default="",
                   help="language of generated files (default: en, or $M8SHIFT_LANG)")
    i.add_argument("--force", action="store_true", help="also reset the relay file")
    i.set_defaults(fn=cmd_init)

    st = sub.add_parser("status")
    st.add_argument("--json", action="store_true", help="machine-readable status (stdlib json)")
    st.set_defaults(fn=cmd_status)

    rc = sub.add_parser("recap", help="read-only briefing: LOCK + last N turns + memory + tasks")
    rc.add_argument("--turns", type=int, default=6)
    rc.add_argument("--memory", type=int, default=5, help="memory headlines to show (<=0 = all)")
    rc.add_argument("--tasks", type=int, default=5, help="open-task headlines to show (<=0 = all)")
    rc.set_defaults(fn=cmd_recap)

    pk = sub.add_parser("peek", help="last handoff addressed to <agent> (rc 3 if not your turn)")
    pk.add_argument("agent")
    pk.set_defaults(fn=cmd_peek)

    lg = sub.add_parser("log", help="read-only relay timeline")
    lg.add_argument("--limit", type=int, default=0, help="show only the last N turns")
    lg.add_argument("--all", action="store_true", help="include archived turns")
    lg.add_argument("--oneline", action="store_true")
    lg.set_defaults(fn=cmd_log)

    w = sub.add_parser("wait")
    w.add_argument("agent")
    w.add_argument("--interval", type=int, default=60)
    w.add_argument("--once", action="store_true", help="check once and exit (rc 3 if not your turn)")
    w.set_defaults(fn=cmd_wait)

    c = sub.add_parser("claim")
    c.add_argument("agent")
    c.add_argument("--force", action="store_true")
    c.add_argument("--check", action="store_true",
                   help="read-only advisory pre-claim probe (no pen taken): readiness + file overlap")
    c.add_argument("--files", default="", help="with --check: files you plan to touch (CSV)")
    c.add_argument("--turns", type=int, default=0,
                   help="with --check: overlap window (<=0 = since your last turn; N = last N turns)")
    c.set_defaults(fn=cmd_claim)

    a = sub.add_parser("append")  # requires WORKING_<agent>: run `claim` first
    a.add_argument("agent")
    a.add_argument("--to", required=True)
    a.add_argument("--ask", default="")
    a.add_argument("--done", default="")
    a.add_argument("--files", default="")
    a.add_argument("--body", default="")
    # §5 advisory turn fields (optional, passthrough): sugar flags + open namespace
    a.add_argument("--branch", default="")
    a.add_argument("--commit", default="")
    a.add_argument("--tests", default="")
    a.add_argument("--next", default="")
    a.add_argument("--blocked-on", dest="blocked_on", default="")
    a.add_argument("--field", action="append", default=[], metavar="KEY=VALUE",
                   help="advisory turn field, repeatable (KEY snake_case or x_*)")
    a.set_defaults(fn=cmd_append)

    rm = sub.add_parser("remember",
                        help="append one durable note to M8SHIFT.memory.md (no pen needed)")
    rm.add_argument("agent")
    rm.add_argument("note")
    rm.set_defaults(fn=cmd_remember)

    tk = sub.add_parser("task", help="shared append-only to-do ledger (no pen needed)")
    tk.set_defaults(fn=cmd_task)
    tk_sub = tk.add_subparsers(dest="verb", required=True)
    tk_add = tk_sub.add_parser("add", help="append a task")
    tk_add.add_argument("agent")
    tk_add.add_argument("desc")
    tk_add.add_argument("--for", dest="for_", default="", help="advisory assignee (roster name)")
    tk_add.add_argument("--blocked-on", dest="blocked_on", default="",
                        help="advisory wait reason (free text — never enforced or resolved)")
    for v in ("done", "drop"):
        tp = tk_sub.add_parser(v, help=f"append a {v} event for a task id")
        tp.add_argument("agent")
        tp.add_argument("id", type=int)
    tk_list = tk_sub.add_parser("list", help="open tasks (--all includes done/drop)")
    tk_list.add_argument("--all", action="store_true")
    tk_show = tk_sub.add_parser("show", help="event history of one task id")
    tk_show.add_argument("id", type=int)

    r = sub.add_parser("release")
    r.add_argument("agent")
    r.add_argument("--to", required=True)
    r.add_argument("--force", action="store_true")
    r.set_defaults(fn=cmd_release)

    d = sub.add_parser("done")
    d.add_argument("agent")
    d.add_argument("--force", action="store_true")
    d.set_defaults(fn=cmd_done)

    ar = sub.add_parser("archive")
    ar.add_argument("--keep", type=int, default=6)
    ar.set_defaults(fn=cmd_archive)

    args = p.parse_args()
    # ROSTER/LANG are resolved per command by load_or_die (and by cmd_init), under
    # the file lock, so agent validation always matches the on-disk roster.
    sys.exit(args.fn(args))

if __name__ == "__main__":
    main()
